<?php return array (
  'All assets' => 'جميع الملفات',
  'Asset actions' => 'إجراءات الملف',
  'Asset file updated!' => 'تم تحديث الملف!',
  'Asset link copied!' => 'تم نسخ رابط الملف!',
  'Asset removed!' => 'تمت إزالة الملف!',
  'Asset updated!' => 'تم تحديث الملف!',
  'Assets removed!' => 'تمت إزالة الملفات!',
  'Color copied!' => 'تم نسخ اللون!',
  'Copy asset link' => 'نسخ رابط الملف',
  'Edit asset' => 'تحرير الملف',
  'Folder' => 'مجلد',
  'Folder icon' => 'أيقونة المجلد',
  'Folder name' => 'اسم المجلد',
  'Folder name contains invalid characters' => 'يحتوي اسم المجلد على أحرف غير صالحة',
  'Folder name is required' => 'اسم المجلد مطلوب',
  'Folder removed!' => 'تمت إزالة المجلد!',
  'Go to assets' => 'الذهاب إلى الملفات',
  'Latest uploaded assets' => 'أحدث الملفات المحملة',
  'Mime' => 'Mime',
  'No asset selected' => 'لم يتم تحديد ملف',
  'No assets' => 'لا توجد ملفات',
  'Parent folder' => 'المجلد الأصلي',
  'Select' => 'تحديد',
  'Upload asset' => 'تحميل ملف',
  'Upload failed for:' => 'فشل التحميل لـ:',
  'none' => 'لا شيء',
);