<?php return array (
  'Choose suggestion' => 'اختر الاقتراح',
  'Create project' => 'إنشاء مشروع',
  'Edit project' => 'تحرير المشروع',
  'Filtered keys' => 'المفاتيح المصفاة',
  'Key' => 'مفتاح',
  'Key actions' => 'إجراءات المفتاح',
  'Key already exists!' => 'المفتاح موجود بالفعل!',
  'Key editor' => 'محرر المفاتيح',
  'Keys' => 'مفاتيح',
  'Keys imported' => 'تم استيراد المفاتيح',
  'Lokalize' => 'تعريب',
  'No keys defined' => 'لم يتم تعريف مفاتيح',
  'No project created yet' => 'لم يتم إنشاء مشروع بعد',
  'No projects' => 'لا توجد مشاريع',
  'Non visible' => 'غير مرئي',
  'One' => 'واحد',
  'Please add some locales!' => 'الرجاء إضافة بعض اللغات!',
  'Project' => 'مشروع',
  'Project created!' => 'تم إنشاء المشروع!',
  'Project updated!' => 'تم تحديث المشروع!',
  'Save key' => 'حفظ المفتاح',
  'Save project' => 'حفظ المشروع',
  'Target language' => 'اللغة المستهدفة',
  'Text Translation' => 'ترجمة النص',
  'Translate' => 'ترجمة',
  'Update project' => 'تحديث المشروع',
);