<?php return array (
  'Add header' => 'إضافة رأس',
  'Calling webhook url' => 'جاري الاتصال برابط Webhook',
  'Create webhook' => 'إنشاء Webhook',
  'Custom headers' => 'رؤوس مخصصة',
  'Edit webhook' => 'تحرير Webhook',
  'HTTP body' => 'جسم HTTP',
  'HTTP settings' => 'إعدادات HTTP',
  'No custom headers defined' => 'لم يتم تعريف رؤوس مخصصة',
  'No webhooks' => 'لا توجد Webhooks',
  'Payload' => 'الحمولة',
  'Request Method' => 'طريقة الطلب',
  'Trigger webhook' => 'تشغيل Webhook',
  'Update webhook' => 'تحديث Webhook',
  'Webhook created!' => 'تم إنشاء Webhook!',
  'Webhook finished' => 'انتهى Webhook',
  'Webhook updated!' => 'تم تحديث Webhook!',
  'Webhooks' => 'Webhooks',
);