<?php return array (
  'All assets' => 'Všechny soubory',
  'Asset actions' => 'Akce se soubory',
  'Asset file updated!' => 'Soubor aktualizován!',
  'Asset link copied!' => 'Odkaz na soubor zkopírován!',
  'Asset removed!' => 'Soubor odstraněn!',
  'Asset updated!' => 'Soubor aktualizován!',
  'Assets removed!' => 'Soubory odstraněny!',
  'Color copied!' => 'Barva zkopírována!',
  'Copy asset link' => 'Kopírovat odkaz na soubor',
  'Edit asset' => 'Upravit soubor',
  'Folder' => 'Složka',
  'Folder icon' => 'Ikona složky',
  'Folder name' => 'Název složky',
  'Folder name contains invalid characters' => 'Název složky obsahuje neplatné znaky',
  'Folder name is required' => 'Název složky je povinný',
  'Folder removed!' => 'Složka odstraněna!',
  'Go to assets' => 'Přejít na soubory',
  'Latest uploaded assets' => 'Naposledy nahrané soubory',
  'Mime' => 'Mime',
  'No asset selected' => 'Nebyl vybrán žádný soubor',
  'No assets' => 'Žádné soubory',
  'Parent folder' => 'Nadřazená složka',
  'Select' => 'Vybrat',
  'Upload asset' => 'Nahrát soubor',
  'Upload failed for:' => 'Nahrávání selhalo pro:',
  'none' => 'žádný',
);