<?php return array (
  'Add header' => 'Přidat hlavičku',
  'Calling webhook url' => 'Volání URL webhooku',
  'Create webhook' => 'Vytvořit webhook',
  'Custom headers' => 'Vlastní hlavičky',
  'Edit webhook' => 'Upravit webhook',
  'HTTP body' => 'HTTP tělo',
  'HTTP settings' => 'Nastavení HTTP',
  'No custom headers defined' => 'Nebyly definovány žádné vlastní hlavičky',
  'No webhooks' => 'Žádné webhooky',
  'Payload' => 'Payload',
  'Request Method' => 'Metoda požadavku',
  'Trigger webhook' => 'Spustit webhook',
  'Update webhook' => 'Aktualizovat webhook',
  'Webhook created!' => 'Webhook vytvořen!',
  'Webhook finished' => 'Webhook dokončen',
  'Webhook updated!' => 'Webhook aktualizován!',
  'Webhooks' => 'Webhooky',
);