<?php return [
  'All assets' => 'Alle Dateien',
  'Asset actions' => 'Datei-Aktionen',
  'Asset file updated!' => 'Datei aktualisiert!',
  'Asset link copied!' => 'Link zur Datei kopiert!',
  'Asset removed!' => 'Datei gelöscht!',
  'Asset updated!' => 'Datei aktualisiert!',
  'Assets removed!' => 'Dateien gelöscht!',
  'Color copied!' => 'Farbe kopiert!',
  'Copy asset link' => 'Link zur Datei kopieren',
  'Edit asset' => 'Datei bearbeiten',
  'Folder' => 'Ordner',
  'Folder icon' => 'Ordner-Icon',
  'Folder name' => 'Ordnername',
  'Folder name contains invalid characters' => 'Ordnername enthält ungültige Zeichen',
  'Folder name is required' => 'Ordnername ist erforderlich',
  'Folder removed!' => 'Ordner gelöscht!',
  'Go to assets' => 'Zu den Dateien',
  'Latest uploaded assets' => 'Zuletzt hochgeladene Dateien',
  'Mime' => 'Mime',
  'No asset selected' => 'Keine Datei ausgewählt',
  'No assets' => 'Keine Dateien',
  'Parent folder' => 'Übergeordneter Ordner',
  'Select' => 'Auswählen',
  'Upload asset' => 'Datei hochladen',
  'Upload failed for:' => 'Upload fehlgeschlagen für:',
  'none' => 'keine',
];