<?php return [
  'Create file' => 'Datei erstellen',
  'Create folder' => 'Ordner erstellen',
  'Delete' => 'Löschen',
  'Download' => 'Herunterladen',
  'Edit' => 'Bearbeiten',
  'Edit file' => 'Datei bearbeiten',
  'Empty' => 'Leer',
  'File actions' => 'Datei-Aktionen',
  'File updated!' => 'Datei aktualisiert!',
  'File(s) deleted' => 'Datei(en) gelöscht',
  'File(s) size exceeds max upload size limit!' => 'Die Größe der Datei(en) überschreitet die maximale Upload-Größe!',
  'Finder' => 'Finder',
  'Folder actions' => 'Ordner-Aktionen',
  'Item(s) deleted' => 'Element(e) gelöscht',
  'Link file' => 'Datei verknüpfen',
  'Name' => 'Name',
  'No file linked' => 'Keine Datei verlinkt',
  'Readonly' => 'Schreibgeschützt',
  'Rename' => 'Umbenennen',
  'Reset' => 'Zurücksetzen',
  'Select file' => 'Datei auswählen',
  'Settings' => 'Settings',
  'Size' => 'Größe',
  'Updated' => 'Aktualisiert',
  'Upload failed!' => 'Upload fehlgeschlagen!',
  'Upload file' => 'Datei hochladen',
];
