<?php return [
  'Choose suggestion' => 'Vorschlag wählen',
  'Create project' => 'Projekt erstellen',
  'Edit project' => 'Projekt bearbeiten',
  'Filtered keys' => 'Gefilterte Schlüssel',
  'Key' => 'Schlüssel',
  'Key actions' => 'Schlüssel-Aktionen',
  'Key already exists!' => 'Schlüssel existiert bereits!',
  'Key editor' => 'Schlüssel-Editor',
  'Keys' => 'Schlüssel',
  'Keys imported' => 'Schlüssel importiert',
  'Lokalize' => 'Lokalize',
  'No keys defined' => 'Keine Schlüssel definiert',
  'No project created yet' => 'Noch kein Projekt erstellt',
  'No projects' => 'Keine Projekte',
  'Non visible' => 'Nicht sichtbar',
  'One' => 'Eins',
  'Please add some locales!' => 'Bitte fügen Sie einige Sprachen hinzu!',
  'Project' => 'Projekt',
  'Project created!' => 'Projekt erstellt!',
  'Project updated!' => 'Projekt aktualisiert!',
  'Save key' => 'Schlüssel speichern',
  'Save project' => 'Projekt speichern',
  'Target language' => 'Zielsprache',
  'Text Translation' => 'Textübersetzung',
  'Translate' => 'Übersetzen',
  'Update project' => 'Projekt aktualisieren',
];