<?php return [
  'Add event' => 'Ereignis hinzufügen',
  'Add header' => 'Kopfzeile hinzufügen',
  'Create webhook' => 'Webhook erstellen',
  'Custom headers' => 'Benutzerdefinierte Kopfzeilen',
  'Delete' => 'Löschen',
  'Edit' => 'bearbeiten',
  'Edit webhook' => 'Webhook bearbeiten',
  'Events' => 'Ereignisse',
  'HTTP body' => 'HTTP-Körper',
  'HTTP settings' => 'HTTP-Einstellungen',
  'Name' => 'Name',
  'No custom headers defined' => 'Keine eigenen Kopfzeilen definiert',
  'No events defined' => 'Keine Ereignisse definiert',
  'No webhooks' => 'Keine Webhooks',
  'Payload' => 'Nutzdaten',
  'Request Method' => 'Anfrage Methode',
  'Settings' => 'Settings',
  'Trigger webhook' => 'Webhook auslösen',
  'Update webhook' => 'Webhook aktualisieren',
  'Url' => 'Url',
  'Webhook created!' => 'Webhook erstellt!',
  'Webhook triggered!' => 'Webhook ausgelöst!',
  'Webhook updated!' => 'Webhook aktualisiert!',
  'Webhooks' => 'Webhooks',
];
