<?php return [
  'Add header' => 'Header hinzufügen',
  'Calling webhook url' => 'Webhook-URL wird aufgerufen',
  'Create webhook' => 'Webhook erstellen',
  'Custom headers' => 'Benutzerdefinierte Header',
  'Edit webhook' => 'Webhook bearbeiten',
  'HTTP body' => 'HTTP Body',
  'HTTP settings' => 'HTTP-Einstellungen',
  'No custom headers defined' => 'Keine benutzerdefinierten Header definiert',
  'No webhooks' => 'Keine Webhooks',
  'Payload' => 'Payload',
  'Request Method' => 'Request-Methode',
  'Trigger webhook' => 'Webhook auslösen',
  'Update webhook' => 'Webhook aktualisieren',
  'Webhook created!' => 'Webhook erstellt!',
  'Webhook finished' => 'Webhook abgeschlossen',
  'Webhook updated!' => 'Webhook aktualisiert!',
  'Webhooks' => 'Webhooks',
];