<?php return array (
  'All assets' => 'Alle filer',
  'Asset actions' => 'Filhandlinger',
  'Asset file updated!' => 'Fil oppdatert!',
  'Asset link copied!' => 'Fillenke kopiert!',
  'Asset removed!' => 'Fil fjernet!',
  'Asset updated!' => 'Fil oppdatert!',
  'Assets removed!' => 'Filer fjernet!',
  'Color copied!' => 'Farge kopiert!',
  'Copy asset link' => 'Kopier fillenke',
  'Edit asset' => 'Rediger fil',
  'Folder' => 'Mappe',
  'Folder icon' => 'Mappeikon',
  'Folder name' => 'Mappenavn',
  'Folder name contains invalid characters' => 'Mappenavnet inneholder ugyldige tegn',
  'Folder name is required' => 'Mappenavn er påkrevd',
  'Folder removed!' => 'Mappe fjernet!',
  'Go to assets' => 'Gå til filer',
  'Latest uploaded assets' => 'Sist lastet opp filer',
  'Mime' => 'Mime',
  'No asset selected' => 'Ingen fil valgt',
  'No assets' => 'Ingen filer',
  'Parent folder' => 'Overordnet mappe',
  'Select' => 'Velg',
  'Upload asset' => 'Last opp fil',
  'Upload failed for:' => 'Opplasting mislyktes for:',
  'none' => 'ingen',
);