<?php return array (
  'Choose suggestion' => 'Velg forslag',
  'Create project' => 'Opprett prosjekt',
  'Edit project' => 'Rediger prosjekt',
  'Filtered keys' => 'Filtrerte nøkler',
  'Key' => 'Nøkkel',
  'Key actions' => 'Nøkkelhandlinger',
  'Key already exists!' => 'Nøkkel eksisterer allerede!',
  'Key editor' => 'Nøkkelredigerer',
  'Keys' => 'Nøkler',
  'Keys imported' => 'Nøkler importert',
  'Lokalize' => 'Lokalize',
  'No keys defined' => 'Ingen nøkler definert',
  'No project created yet' => 'Inget prosjekt opprettet ennå',
  'No projects' => 'Ingen prosjekter',
  'Non visible' => 'Ikke synlig',
  'One' => 'En',
  'Please add some locales!' => 'Vennligst legg til noen språk!',
  'Project' => 'Prosjekt',
  'Project created!' => 'Prosjekt opprettet!',
  'Project updated!' => 'Prosjekt oppdatert!',
  'Save key' => 'Lagre nøkkel',
  'Save project' => 'Lagre prosjekt',
  'Target language' => 'Målspråk',
  'Text Translation' => 'Tekstoversettelse',
  'Translate' => 'Oversett',
  'Update project' => 'Oppdater prosjekt',
);