<?php return array (
  'Add header' => 'Legg til overskrift',
  'Calling webhook url' => 'Kaller webhook-url',
  'Create webhook' => 'Opprett webhook',
  'Custom headers' => 'Tilpassede overskrifter',
  'Edit webhook' => 'Rediger webhook',
  'HTTP body' => 'HTTP-kropp',
  'HTTP settings' => 'HTTP-innstillinger',
  'No custom headers defined' => 'Ingen tilpassede overskrifter definert',
  'No webhooks' => 'Ingen webhooks',
  'Payload' => 'Payload',
  'Request Method' => 'Forespørselsmetode',
  'Trigger webhook' => 'Utløs webhook',
  'Update webhook' => 'Oppdater webhook',
  'Webhook created!' => 'Webhook opprettet!',
  'Webhook finished' => 'Webhook ferdig',
  'Webhook updated!' => 'Webhook oppdatert!',
  'Webhooks' => 'Webhooks',
);