<?php return array (
  'All assets' => 'Wszystkie pliki',
  'Asset actions' => 'Akcje plików',
  'Asset file updated!' => 'Plik zaktualizowany!',
  'Asset link copied!' => 'Link do pliku skopiowany!',
  'Asset removed!' => 'Plik usunięty!',
  'Asset updated!' => 'Plik zaktualizowany!',
  'Assets removed!' => 'Pliki usunięte!',
  'Color copied!' => 'Kolor skopiowany!',
  'Copy asset link' => 'Kopiuj link do pliku',
  'Edit asset' => 'Edytuj plik',
  'Folder' => 'Folder',
  'Folder icon' => 'Ikona folderu',
  'Folder name' => 'Nazwa folderu',
  'Folder name contains invalid characters' => 'Nazwa folderu zawiera nieprawidłowe znaki',
  'Folder name is required' => 'Nazwa folderu jest wymagana',
  'Folder removed!' => 'Folder usunięty!',
  'Go to assets' => 'Przejdź do plików',
  'Latest uploaded assets' => 'Ostatnio przesłane pliki',
  'Mime' => 'Mime',
  'No asset selected' => 'Nie wybrano pliku',
  'No assets' => 'Brak plików',
  'Parent folder' => 'Folder nadrzędny',
  'Select' => 'Wybierz',
  'Upload asset' => 'Prześlij plik',
  'Upload failed for:' => 'Przesyłanie nieudane dla:',
  'none' => 'brak',
);