<?php return [
    'Create file' => 'Utwórz plik',
    'Create folder' => 'Utwórz folder',
    'Delete' => 'Usuń',
    'Download' => 'Pobierz',
    'Edit' => 'Edytuj',
    'Edit file' => 'Edytuj plik',
    'Empty' => 'Pusty',
    'File actions' => 'Akcje pliku',
    'File updated!' => 'Plik zaktualizowany!',
    'File(s) deleted' => 'Plik(i) usunięty(e)',
    'File(s) size exceeds max upload size limit!' => 'Rozmiar pliku(ów) przekracza limit maksymalnego rozmiaru przesyłania!',
    'Finder' => 'Eksplorator',
    'Folder actions' => 'Akcje folderu',
    'Item(s) deleted' => 'Element(y) usunięty(e)',
    'Link file' => 'Połącz plik',
    'Name' => 'Nazwa',
    'No file linked' => 'Brak połączonego pliku',
    'Readonly' => 'Tylko do odczytu',
    'Rename' => 'Zmień nazwę',
    'Reset' => 'Zresetuj',
    'Select file' => 'Wybierz plik',
    'Settings' => 'Ustawienia',
    'Size' => 'Rozmiar',
    'Updated' => 'Zaktualizowano',
    'Upload failed!' => 'Przesyłanie nie powiodło się!',
    'Upload file' => 'Prześlij plik',
];
