<?php return array (
  'Add header' => 'Dodaj nagłówek',
  'Calling webhook url' => 'Wywoływanie URL webhooka',
  'Create webhook' => 'Utwórz webhook',
  'Custom headers' => 'Niestandardowe nagłówki',
  'Edit webhook' => 'Edytuj webhook',
  'HTTP body' => 'Ciało HTTP',
  'HTTP settings' => 'Ustawienia HTTP',
  'No custom headers defined' => 'Nie zdefiniowano niestandardowych nagłówków',
  'No webhooks' => 'Brak webhooków',
  'Payload' => 'Payload',
  'Request Method' => 'Metoda Żądania',
  'Trigger webhook' => 'Wyzwól webhook',
  'Update webhook' => 'Aktualizuj webhook',
  'Webhook created!' => 'Webhook utworzony!',
  'Webhook finished' => 'Webhook zakończony',
  'Webhook updated!' => 'Webhook zaktualizowany!',
  'Webhooks' => 'Webhooki',
);