<?php return [
    'Add event' => 'Dodaj zdarzenie',
    'Add header' => 'Dodaj nagłówek',
    'Create webhook' => 'Utwórz webhook',
    'Custom headers' => 'Niestandardowe nagłówki',
    'Delete' => 'Usuń',
    'Edit' => 'Edytuj',
    'Edit webhook' => 'Edytuj webhook',
    'Events' => 'Zdarzenia',
    'HTTP body' => 'Treść HTTP',
    'HTTP settings' => 'Ustawienia HTTP',
    'Name' => 'Nazwa',
    'No custom headers defined' => 'Brak zdefiniowanych niestandardowych nagłówków',
    'No events defined' => 'Brak zdefiniowanych zdarzeń',
    'No webhooks' => 'Brak webhooków',
    'Payload' => 'Ładunek',
    'Request Method' => 'Metoda żądania',
    'Settings' => 'Ustawienia',
    'Trigger webhook' => 'Aktywuj webhook',
    'Update webhook' => 'Aktualizuj webhook',
    'Url' => 'URL',
    'Webhook created!' => 'Webhook utworzony!',
    'Webhook triggered!' => 'Webhook aktywowany!',
    'Webhook updated!' => 'Webhook zaktualizowany!',
    'Webhooks' => 'Webhooki',
];
