<?php return array (
  'All assets' => 'Kaikki tiedostot',
  'Asset actions' => 'Tiedostotoiminnot',
  'Asset file updated!' => 'Tiedosto päivitetty!',
  'Asset link copied!' => 'Tiedoston linkki kopioitu!',
  'Asset removed!' => 'Tiedosto poistettu!',
  'Asset updated!' => 'Tiedosto päivitetty!',
  'Assets removed!' => 'Tiedostot poistettu!',
  'Color copied!' => 'Väri kopioitu!',
  'Copy asset link' => 'Kopioi tiedoston linkki',
  'Edit asset' => 'Muokkaa tiedostoa',
  'Folder' => 'Kansio',
  'Folder icon' => 'Kansion kuvake',
  'Folder name' => 'Kansion nimi',
  'Folder name contains invalid characters' => 'Kansion nimi sisältää virheellisiä merkkejä',
  'Folder name is required' => 'Kansion nimi on pakollinen',
  'Folder removed!' => 'Kansio poistettu!',
  'Go to assets' => 'Siirry tiedostoihin',
  'Latest uploaded assets' => 'Viimeksi ladatut tiedostot',
  'Mime' => 'Mime',
  'No asset selected' => 'Tiedostoa ei valittu',
  'No assets' => 'Ei tiedostoja',
  'Parent folder' => 'Yläkansio',
  'Select' => 'Valitse',
  'Upload asset' => 'Lataa tiedosto',
  'Upload failed for:' => 'Lataus epäonnistui:',
  'none' => 'ei mitään',
);