<?php return array (
  'Choose suggestion' => 'Valitse ehdotus',
  'Create project' => 'Luo projekti',
  'Edit project' => 'Muokkaa projektia',
  'Filtered keys' => 'Suodatetut avaimet',
  'Key' => 'Avain',
  'Key actions' => 'Avaimen toiminnot',
  'Key already exists!' => 'Avain on jo olemassa!',
  'Key editor' => 'Avaineditori',
  'Keys' => 'Avaimet',
  'Keys imported' => 'Avaimet tuotu',
  'Lokalize' => 'Lokalize',
  'No keys defined' => 'Avaimia ei ole määritetty',
  'No project created yet' => 'Projektia ei ole vielä luotu',
  'No projects' => 'Ei projekteja',
  'Non visible' => 'Ei näkyvissä',
  'One' => 'Yksi',
  'Please add some locales!' => 'Lisää kieliä!',
  'Project' => 'Projekti',
  'Project created!' => 'Projekti luotu!',
  'Project updated!' => 'Projekti päivitetty!',
  'Save key' => 'Tallenna avain',
  'Save project' => 'Tallenna projekti',
  'Target language' => 'Kohdekieli',
  'Text Translation' => 'Tekstin käännös',
  'Translate' => 'Käännä',
  'Update project' => 'Päivitä projekti',
);