<?php return array (
  'Add header' => 'Lisää otsikko',
  'Calling webhook url' => 'Kutsutaan webhookin URL-osoitetta',
  'Create webhook' => 'Luo webhook',
  'Custom headers' => 'Mukautetut otsikot',
  'Edit webhook' => 'Muokkaa webhookia',
  'HTTP body' => 'HTTP-runko',
  'HTTP settings' => 'HTTP-asetukset',
  'No custom headers defined' => 'Mukautettuja otsikoita ei ole määritetty',
  'No webhooks' => 'Ei webhookeja',
  'Payload' => 'Hyötykuorma',
  'Request Method' => 'Pyyntötapa',
  'Trigger webhook' => 'Käynnistä webhook',
  'Update webhook' => 'Päivitä webhook',
  'Webhook created!' => 'Webhook luotu!',
  'Webhook finished' => 'Webhook valmis',
  'Webhook updated!' => 'Webhook päivitetty!',
  'Webhooks' => 'Webhookit',
);