<?php return array (
  'All assets' => 'Όλοι οι πόροι',
  'Asset actions' => 'Ενέργειες πόρων',
  'Asset file updated!' => 'Το αρχείο πόρου ενημερώθηκε!',
  'Asset link copied!' => 'Ο σύνδεσμος πόρου αντιγράφηκε!',
  'Asset removed!' => 'Ο πόρος αφαιρέθηκε!',
  'Asset updated!' => 'Ο πόρος ενημερώθηκε!',
  'Assets removed!' => 'Οι πόροι αφαιρέθηκαν!',
  'Color copied!' => 'Το χρώμα αντιγράφηκε!',
  'Copy asset link' => 'Αντιγραφή συνδέσμου πόρου',
  'Edit asset' => 'Επεξεργασία πόρου',
  'Folder' => 'Φάκελος',
  'Folder icon' => 'Εικονίδιο φακέλου',
  'Folder name' => 'Όνομα φακέλου',
  'Folder name contains invalid characters' => 'Το όνομα φακέλου περιέχει μη έγκυρους χαρακτήρες',
  'Folder name is required' => 'Το όνομα φακέλου είναι υποχρεωτικό',
  'Folder removed!' => 'Ο φάκελος αφαιρέθηκε!',
  'Go to assets' => 'Μετάβαση στους πόρους',
  'Latest uploaded assets' => 'Τελευαίοι μεταφορτωμένοι πόροι',
  'Mime' => 'Mime',
  'No asset selected' => 'Δεν έχει επιλεγεί πόρος',
  'No assets' => 'Δεν υπάρχουν πόροι',
  'Parent folder' => 'Γονικός φάκελος',
  'Select' => 'Επιλογή',
  'Upload asset' => 'Μεταφόρτωση πόρου',
  'Upload failed for:' => 'Η μεταφόρτωση απέτυχε για:',
  'none' => 'κανένα',
);