<?php return array (
  'Choose suggestion' => 'Επιλογή πρότασης',
  'Create project' => 'Δημιουργία έργου',
  'Edit project' => 'Επεξεργασία έργου',
  'Filtered keys' => 'Φιλτραρισμένα κλειδιά',
  'Key' => 'Κλειδί',
  'Key actions' => 'Ενέργειες κλειδιού',
  'Key already exists!' => 'Το κλειδί υπάρχει ήδη!',
  'Key editor' => 'Επεξεργαστής κλειδιών',
  'Keys' => 'Κλειδιά',
  'Keys imported' => 'Τα κλειδιά εισήχθησαν',
  'Lokalize' => 'Lokalize',
  'No keys defined' => 'Δεν έχουν οριστεί κλειδιά',
  'No project created yet' => 'Δεν έχει δημιουργηθεί έργο ακόμα',
  'No projects' => 'Δεν υπάρχουν έργα',
  'Non visible' => 'Μη ορατό',
  'One' => 'Ένα',
  'Please add some locales!' => 'Παρακαλώ προσθέστε μερικές γλώσσες!',
  'Project' => 'Έργο',
  'Project created!' => 'Το έργο δημιουργήθηκε!',
  'Project updated!' => 'Το έργο ενημερώθηκε!',
  'Save key' => 'Αποθήκευση κλειδιού',
  'Save project' => 'Αποθήκευση έργου',
  'Target language' => 'Γλώσσα στόχος',
  'Text Translation' => 'Μετάφραση Κειμένου',
  'Translate' => 'Μετάφραση',
  'Update project' => 'Ενημέρωση έργου',
);