<?php return array (
  'Add header' => 'Προσθήκη κεφαλίδας',
  'Calling webhook url' => 'Κλήση URL webhook',
  'Create webhook' => 'Δημιουργία webhook',
  'Custom headers' => 'Προσαρμοσμένες κεφαλίδες',
  'Edit webhook' => 'Επεξεργασία webhook',
  'HTTP body' => 'Σώμα HTTP',
  'HTTP settings' => 'Ρυθμίσεις HTTP',
  'No custom headers defined' => 'Δεν έχουν οριστεί προσαρμοσμένες κεφαλίδες',
  'No webhooks' => 'Δεν υπάρχουν webhooks',
  'Payload' => 'Φορτίο',
  'Request Method' => 'Μέθοδος Αιτήματος',
  'Trigger webhook' => 'Ενεργοποίηση webhook',
  'Update webhook' => 'Ενημέρωση webhook',
  'Webhook created!' => 'Το webhook δημιουργήθηκε!',
  'Webhook finished' => 'Το webhook ολοκληρώθηκε',
  'Webhook updated!' => 'Το webhook ενημερώθηκε!',
  'Webhooks' => 'Webhooks',
);