<?php return array (
  'All assets' => 'Összes fájl',
  'Asset actions' => 'Fájlműveletek',
  'Asset file updated!' => 'Fájl frissítve!',
  'Asset link copied!' => 'Fájl hivatkozása másolva!',
  'Asset removed!' => 'Fájl eltávolítva!',
  'Asset updated!' => 'Fájl frissítve!',
  'Assets removed!' => 'Fájlok eltávolítva!',
  'Color copied!' => 'Szín másolva!',
  'Copy asset link' => 'Fájl hivatkozás másolása',
  'Edit asset' => 'Fájl szerkesztése',
  'Folder' => 'Mappa',
  'Folder icon' => 'Mappa ikon',
  'Folder name' => 'Mappa neve',
  'Folder name contains invalid characters' => 'A mappa neve érvénytelen karaktereket tartalmaz',
  'Folder name is required' => 'A mappa neve kötelező',
  'Folder removed!' => 'Mappa eltávolítva!',
  'Go to assets' => 'Ugrás a fájlokhoz',
  'Latest uploaded assets' => 'Legutóbb feltöltött fájlok',
  'Mime' => 'Mime',
  'No asset selected' => 'Nincs fájl kiválasztva',
  'No assets' => 'Nincsenek fájlok',
  'Parent folder' => 'Szülő mappa',
  'Select' => 'Kiválasztás',
  'Upload asset' => 'Fájl feltöltése',
  'Upload failed for:' => 'Feltöltés sikertelen:',
  'none' => 'nincs',
);