<?php return array (
  'Choose suggestion' => 'Válasszon javaslatot',
  'Create project' => 'Projekt létrehozása',
  'Edit project' => 'Projekt szerkesztése',
  'Filtered keys' => 'Szűrt kulcsok',
  'Key' => 'Kulcs',
  'Key actions' => 'Kulcs műveletek',
  'Key already exists!' => 'A kulcs már létezik!',
  'Key editor' => 'Kulcsszerkesztő',
  'Keys' => 'Kulcsok',
  'Keys imported' => 'Kulcsok importálva',
  'Lokalize' => 'Lokalizálás',
  'No keys defined' => 'Nincsenek kulcsok definiálva',
  'No project created yet' => 'Még nincs létrehozva projekt',
  'No projects' => 'Nincsenek projektek',
  'Non visible' => 'Nem látható',
  'One' => 'Egy',
  'Please add some locales!' => 'Kérjük, adjon hozzá nyelveket!',
  'Project' => 'Projekt',
  'Project created!' => 'Projekt létrehozva!',
  'Project updated!' => 'Projekt frissítve!',
  'Save key' => 'Kulcs mentése',
  'Save project' => 'Projekt mentése',
  'Target language' => 'Célnyelv',
  'Text Translation' => 'Szövegfordítás',
  'Translate' => 'Fordítás',
  'Update project' => 'Projekt frissítése',
);