<?php return array (
  'Add header' => 'Fejléc hozzáadása',
  'Calling webhook url' => 'Webhook URL hívása',
  'Create webhook' => 'Webhook létrehozása',
  'Custom headers' => 'Egyéni fejlécek',
  'Edit webhook' => 'Webhook szerkesztése',
  'HTTP body' => 'HTTP törzs',
  'HTTP settings' => 'HTTP beállítások',
  'No custom headers defined' => 'Nincsenek definiálva egyéni fejlécek',
  'No webhooks' => 'Nincsenek webhookok',
  'Payload' => 'Adattartalom',
  'Request Method' => 'Kérés módja',
  'Trigger webhook' => 'Webhook indítása',
  'Update webhook' => 'Webhook frissítése',
  'Webhook created!' => 'Webhook létrehozva!',
  'Webhook finished' => 'Webhook befejezve',
  'Webhook updated!' => 'Webhook frissítve!',
  'Webhooks' => 'Webhookok',
);