<?php return array (
  'All assets' => 'Tutti i file',
  'Asset actions' => 'Azioni file',
  'Asset file updated!' => 'File aggiornato!',
  'Asset link copied!' => 'Link file copiato!',
  'Asset removed!' => 'File rimosso!',
  'Asset updated!' => 'File aggiornato!',
  'Assets removed!' => 'File rimossi!',
  'Color copied!' => 'Colore copiato!',
  'Copy asset link' => 'Copia link file',
  'Edit asset' => 'Modifica file',
  'Folder' => 'Cartella',
  'Folder icon' => 'Icona cartella',
  'Folder name' => 'Nome cartella',
  'Folder name contains invalid characters' => 'Il nome della cartella contiene caratteri non validi',
  'Folder name is required' => 'Nome cartella obbligatorio',
  'Folder removed!' => 'Cartella rimossa!',
  'Go to assets' => 'Vai ai file',
  'Latest uploaded assets' => 'Ultimi file caricati',
  'Mime' => 'Mime',
  'No asset selected' => 'Nessun file selezionato',
  'No assets' => 'Nessun file',
  'Parent folder' => 'Cartella padre',
  'Select' => 'Seleziona',
  'Upload asset' => 'Carica file',
  'Upload failed for:' => 'Upload fallito per:',
  'none' => 'nessuno',
);