<?php return [
  'Create file' => 'Crea file',
  'Create folder' => 'Crea cartella',
  'Delete' => 'Elimina',
  'Download' => 'Scarica',
  'Edit' => 'Modifica',
  'Edit file' => 'Modifica file',
  'Empty' => 'Vuoto',
  'File actions' => 'Azioni sui file',
  'File updated!' => 'File aggiornato!',
  'File(s) deleted' => 'File eliminato/i',
  'File(s) size exceeds max upload size limit!' => 'La dimensione dei/del file supera il limite massimo!',
  'Finder' => 'Trova',
  'Folder actions' => 'Azioni sulla cartella',
  'Item(s) deleted' => 'Elemento/i eliminato/i',
  'Link file' => 'Collega file',
  'Name' => 'Nome',
  'No file linked' => 'Nessun file collegato',
  'Readonly' => 'Sola lettura',
  'Rename' => 'Rinomina',
  'Reset' => 'Reimposta',
  'Select file' => 'Seleziona file',
  'Settings' => 'Impostazioni',
  'Size' => 'Dimensione',
  'Updated' => 'Aggiornato',
  'Upload failed!' => 'Caricamento fallito!',
  'Upload file' => 'Carica file',
];
