<?php return array (
  'Choose suggestion' => 'Scegli suggerimento',
  'Create project' => 'Crea progetto',
  'Edit project' => 'Modifica progetto',
  'Filtered keys' => 'Chiavi filtrate',
  'Key' => 'Chiave',
  'Key actions' => 'Azioni chiave',
  'Key already exists!' => 'Chiave già esistente!',
  'Key editor' => 'Editor chiavi',
  'Keys' => 'Chiavi',
  'Keys imported' => 'Chiavi importate',
  'Lokalize' => 'Localizza',
  'No keys defined' => 'Nessuna chiave definita',
  'No project created yet' => 'Nessun progetto ancora creato',
  'No projects' => 'Nessun progetto',
  'Non visible' => 'Non visibile',
  'One' => 'Uno',
  'Please add some locales!' => 'Aggiungi alcune lingue!',
  'Project' => 'Progetto',
  'Project created!' => 'Progetto creato!',
  'Project updated!' => 'Progetto aggiornato!',
  'Save key' => 'Salva chiave',
  'Save project' => 'Salva progetto',
  'Target language' => 'Lingua target',
  'Text Translation' => 'Traduzione Testo',
  'Translate' => 'Traduci',
  'Update project' => 'Aggiorna progetto',
);