<?php return array (
  'Add header' => 'Aggiungi header',
  'Calling webhook url' => 'Chiamata URL webhook',
  'Create webhook' => 'Crea webhook',
  'Custom headers' => 'Header personalizzati',
  'Edit webhook' => 'Modifica webhook',
  'HTTP body' => 'Corpo HTTP',
  'HTTP settings' => 'Impostazioni HTTP',
  'No custom headers defined' => 'Nessun header personalizzato',
  'No webhooks' => 'Nessun webhook',
  'Payload' => 'Payload',
  'Request Method' => 'Metodo Richiesta',
  'Trigger webhook' => 'Attiva webhook',
  'Update webhook' => 'Aggiorna webhook',
  'Webhook created!' => 'Webhook creato!',
  'Webhook finished' => 'Webhook terminato',
  'Webhook updated!' => 'Webhook aggiornato!',
  'Webhooks' => 'Webhooks',
);