<?php return [
  'Add event' => 'Aggiungi evento',
  'Add header' => 'Aggiungi header',
  'Create webhook' => 'Crea webhook',
  'Custom headers' => 'Personalizza gli header',
  'Delete' => 'Elimina',
  'Edit' => 'Modifica',
  'Edit webhook' => 'Modifica webhook',
  'Events' => 'Eventi',
  'HTTP body' => 'Corpo HTTP',
  'HTTP settings' => 'Impostazioni HTTP',
  'Name' => 'Nome',
  'No custom headers defined' => 'Nessun header personalizzato definito',
  'No events defined' => 'Nessun evento definito',
  'No webhooks' => 'Nessun webhooks',
  'Payload' => 'Carico',
  'Request Method' => 'Metodo della richiesta',
  'Settings' => 'Impostazioni',
  'Trigger webhook' => 'Attiva webhook',
  'Update webhook' => 'Aggiorna webhook',
  'Url' => 'Url',
  'Webhook created!' => 'Webhook creato!',
  'Webhook triggered!' => 'Webhook attivato!',
  'Webhook updated!' => 'Webhook aggiornato!',
  'Webhooks' => 'Webhooks',
];
