<?php return array (
  'All assets' => '所有资源',
  'Asset actions' => '资源操作',
  'Asset file updated!' => '资源文件已更新！',
  'Asset link copied!' => '资源链接已复制！',
  'Asset removed!' => '资源已移除！',
  'Asset updated!' => '资源已更新！',
  'Assets removed!' => '资源已移除！',
  'Color copied!' => '颜色已复制！',
  'Copy asset link' => '复制资源链接',
  'Edit asset' => '编辑资源',
  'Folder' => '文件夹',
  'Folder icon' => '文件夹图标',
  'Folder name' => '文件夹名称',
  'Folder name contains invalid characters' => '文件夹名称包含无效字符',
  'Folder name is required' => '文件夹名称为必填项',
  'Folder removed!' => '文件夹已移除！',
  'Go to assets' => '转到资源',
  'Latest uploaded assets' => '最新上传的资源',
  'Mime' => 'Mime',
  'No asset selected' => '未选择资源',
  'No assets' => '无资源',
  'Parent folder' => '父文件夹',
  'Select' => '选择',
  'Upload asset' => '上传资源',
  'Upload failed for:' => '上传失败：',
  'none' => '无',
);