<?php return array (
  'Choose suggestion' => '选择建议',
  'Create project' => '创建项目',
  'Edit project' => '编辑项目',
  'Filtered keys' => '已筛选密钥',
  'Key' => '密钥',
  'Key actions' => '密钥操作',
  'Key already exists!' => '密钥已存在！',
  'Key editor' => '密钥编辑器',
  'Keys' => '密钥',
  'Keys imported' => '密钥已导入',
  'Lokalize' => '本地化',
  'No keys defined' => '未定义密钥',
  'No project created yet' => '尚未创建项目',
  'No projects' => '无项目',
  'Non visible' => '不可见',
  'One' => '一',
  'Please add some locales!' => '请添加一些语言环境！',
  'Project' => '项目',
  'Project created!' => '项目已创建！',
  'Project updated!' => '项目已更新！',
  'Save key' => '保存密钥',
  'Save project' => '保存项目',
  'Target language' => '目标语言',
  'Text Translation' => '文本翻译',
  'Translate' => '翻译',
  'Update project' => '更新项目',
);