<?php return array (
  'Add header' => '添加头部',
  'Calling webhook url' => '正在调用 Webhook URL',
  'Create webhook' => '创建 Webhook',
  'Custom headers' => '自定义头部',
  'Edit webhook' => '编辑 Webhook',
  'HTTP body' => 'HTTP 主体',
  'HTTP settings' => 'HTTP 设置',
  'No custom headers defined' => '未定义自定义头部',
  'No webhooks' => '无 Webhook',
  'Payload' => '有效载荷',
  'Request Method' => '请求方法',
  'Trigger webhook' => '触发 Webhook',
  'Update webhook' => '更新 Webhook',
  'Webhook created!' => 'Webhook 已创建！',
  'Webhook finished' => 'Webhook 完成',
  'Webhook updated!' => 'Webhook 已更新！',
  'Webhooks' => 'Webhook',
);