<?php return array (
  'All assets' => 'Tất cả tài sản',
  'Asset actions' => 'Hành động tài sản',
  'Asset file updated!' => 'Đã cập nhật tệp tài sản!',
  'Asset link copied!' => 'Đã sao chép liên kết tài sản!',
  'Asset removed!' => 'Đã xóa tài sản!',
  'Asset updated!' => 'Đã cập nhật tài sản!',
  'Assets removed!' => 'Đã xóa các tài sản!',
  'Color copied!' => 'Đã sao chép màu!',
  'Copy asset link' => 'Sao chép liên kết tài sản',
  'Edit asset' => 'Chỉnh sửa tài sản',
  'Folder' => 'Thư mục',
  'Folder icon' => 'Biểu tượng thư mục',
  'Folder name' => 'Tên thư mục',
  'Folder name contains invalid characters' => 'Tên thư mục chứa các ký tự không hợp lệ',
  'Folder name is required' => 'Tên thư mục là bắt buộc',
  'Folder removed!' => 'Đã xóa thư mục!',
  'Go to assets' => 'Đến tài sản',
  'Latest uploaded assets' => 'Tài sản tải lên mới nhất',
  'Mime' => 'Mime',
  'No asset selected' => 'Không có tài sản nào được chọn',
  'No assets' => 'Không có tài sản',
  'Parent folder' => 'Thư mục cha',
  'Select' => 'Chọn',
  'Upload asset' => 'Tải lên tài sản',
  'Upload failed for:' => 'Tải lên thất bại cho:',
  'none' => 'không có',
);