<?php return array (
  'Choose suggestion' => 'Chọn gợi ý',
  'Create project' => 'Tạo dự án',
  'Edit project' => 'Chỉnh sửa dự án',
  'Filtered keys' => 'Các khóa đã lọc',
  'Key' => 'Khóa',
  'Key actions' => 'Hành động khóa',
  'Key already exists!' => 'Khóa đã tồn tại!',
  'Key editor' => 'Trình chỉnh sửa khóa',
  'Keys' => 'Các khóa',
  'Keys imported' => 'Đã nhập các khóa',
  'Lokalize' => 'Lokalize',
  'No keys defined' => 'Chưa định nghĩa khóa',
  'No project created yet' => 'Chưa có dự án nào được tạo',
  'No projects' => 'Không có dự án',
  'Non visible' => 'Không hiển thị',
  'One' => 'Một',
  'Please add some locales!' => 'Vui lòng thêm một số ngôn ngữ!',
  'Project' => 'Dự án',
  'Project created!' => 'Đã tạo dự án!',
  'Project updated!' => 'Đã cập nhật dự án!',
  'Save key' => 'Lưu khóa',
  'Save project' => 'Lưu dự án',
  'Target language' => 'Ngôn ngữ đích',
  'Text Translation' => 'Dịch văn bản',
  'Translate' => 'Dịch',
  'Update project' => 'Cập nhật dự án',
);