<?php return array (
  'Add header' => 'Thêm tiêu đề',
  'Calling webhook url' => 'Đang gọi URL webhook',
  'Create webhook' => 'Tạo webhook',
  'Custom headers' => 'Tiêu đề tùy chỉnh',
  'Edit webhook' => 'Chỉnh sửa webhook',
  'HTTP body' => 'Nội dung HTTP',
  'HTTP settings' => 'Cài đặt HTTP',
  'No custom headers defined' => 'Chưa định nghĩa tiêu đề tùy chỉnh',
  'No webhooks' => 'Không có webhook',
  'Payload' => 'Payload',
  'Request Method' => 'Phương thức yêu cầu',
  'Trigger webhook' => 'Kích hoạt webhook',
  'Update webhook' => 'Cập nhật webhook',
  'Webhook created!' => 'Đã tạo webhook!',
  'Webhook finished' => 'Webhook đã hoàn thành',
  'Webhook updated!' => 'Đã cập nhật webhook!',
  'Webhooks' => 'Webhooks',
);