<?php return array (
  'All assets' => 'Всі файли',
  'Asset actions' => 'Дії з файлами',
  'Asset file updated!' => 'Файл оновлено!',
  'Asset link copied!' => 'Посилання на файл скопійовано!',
  'Asset removed!' => 'Файл видалено!',
  'Asset updated!' => 'Файл оновлено!',
  'Assets removed!' => 'Файли видалено!',
  'Color copied!' => 'Колір скопійовано!',
  'Copy asset link' => 'Копіювати посилання на файл',
  'Edit asset' => 'Редагувати файл',
  'Folder' => 'Папка',
  'Folder icon' => 'Іконка папки',
  'Folder name' => 'Ім\'я папки',
  'Folder name contains invalid characters' => 'Ім\'я папки містить недопустимі символи',
  'Folder name is required' => 'Ім\'я папки обов\'язкове',
  'Folder removed!' => 'Папку видалено!',
  'Go to assets' => 'Перейти до файлів',
  'Latest uploaded assets' => 'Останні завантажені файли',
  'Mime' => 'Mime',
  'No asset selected' => 'Файл не вибрано',
  'No assets' => 'Немає файлів',
  'Parent folder' => 'Батьківська папка',
  'Select' => 'Вибрати',
  'Upload asset' => 'Завантажити файл',
  'Upload failed for:' => 'Завантаження не вдалося для:',
  'none' => 'немає',
);