<?php return array (
  'Choose suggestion' => 'Виберіть пропозицію',
  'Create project' => 'Створити проект',
  'Edit project' => 'Редагувати проект',
  'Filtered keys' => 'Відфільтровані ключі',
  'Key' => 'Ключ',
  'Key actions' => 'Дії з ключем',
  'Key already exists!' => 'Ключ вже існує!',
  'Key editor' => 'Редактор ключів',
  'Keys' => 'Ключі',
  'Keys imported' => 'Ключі імпортовано',
  'Lokalize' => 'Локалізація',
  'No keys defined' => 'Ключі не визначено',
  'No project created yet' => 'Проект ще не створено',
  'No projects' => 'Немає проектів',
  'Non visible' => 'Невидимий',
  'One' => 'Один',
  'Please add some locales!' => 'Будь ласка, додайте локалі!',
  'Project' => 'Проект',
  'Project created!' => 'Проект створено!',
  'Project updated!' => 'Проект оновлено!',
  'Save key' => 'Зберегти ключ',
  'Save project' => 'Зберегти проект',
  'Target language' => 'Цільова мова',
  'Text Translation' => 'Переклад тексту',
  'Translate' => 'Перекласти',
  'Update project' => 'Оновити проект',
);