<?php return array (
  'Add header' => 'Додати заголовок',
  'Calling webhook url' => 'Виклик URL вебхука',
  'Create webhook' => 'Створити вебхук',
  'Custom headers' => 'Користувацькі заголовки',
  'Edit webhook' => 'Редагувати вебхук',
  'HTTP body' => 'HTTP тіло',
  'HTTP settings' => 'Налаштування HTTP',
  'No custom headers defined' => 'Користувацькі заголовки не визначено',
  'No webhooks' => 'Немає вебхуків',
  'Payload' => 'Payload',
  'Request Method' => 'Метод запиту',
  'Trigger webhook' => 'Викликати вебхук',
  'Update webhook' => 'Оновити вебхук',
  'Webhook created!' => 'Вебхук створено!',
  'Webhook finished' => 'Вебхук завершено',
  'Webhook updated!' => 'Вебхук оновлено!',
  'Webhooks' => 'Вебхуки',
);