<?php return array (
  'All assets' => 'सभी संपत्ति',
  'Asset actions' => 'संपत्ति क्रियाएं',
  'Asset file updated!' => 'संपत्ति फ़ाइल अपडेट की गई!',
  'Asset link copied!' => 'संपत्ति लिंक कॉपी किया गया!',
  'Asset removed!' => 'संपत्ति हटा दी गई!',
  'Asset updated!' => 'संपत्ति अपडेट की गई!',
  'Assets removed!' => 'संपत्तियां हटा दी गईं!',
  'Color copied!' => 'रंग कॉपी किया गया!',
  'Copy asset link' => 'संपत्ति लिंक कॉपी करें',
  'Edit asset' => 'संपत्ति संपादित करें',
  'Folder' => 'फ़ोल्डर',
  'Folder icon' => 'फ़ोल्डर आइकन',
  'Folder name' => 'फ़ोल्डर का नाम',
  'Folder name contains invalid characters' => 'फ़ोल्डर के नाम में अमान्य वर्ण हैं',
  'Folder name is required' => 'फ़ोल्डर नाम आवश्यक है',
  'Folder removed!' => 'फ़ोल्डर हटा दिया गया!',
  'Go to assets' => 'संपत्ति पर जाएं',
  'Latest uploaded assets' => 'नवीनतम अपलोड की गई संपत्ति',
  'Mime' => 'Mime',
  'No asset selected' => 'कोई संपत्ति चयनित नहीं',
  'No assets' => 'कोई संपत्ति नहीं',
  'Parent folder' => 'पैरेंट फ़ोल्डर',
  'Select' => 'चुनें',
  'Upload asset' => 'संपत्ति अपलोड करें',
  'Upload failed for:' => 'इसके लिए अपलोड विफल:',
  'none' => 'कोई नहीं',
);