<?php return array (
  'Add header' => 'हेडर जोड़ें',
  'Calling webhook url' => 'वेबहुक URL कॉल कर रहा है',
  'Create webhook' => 'वेबहुक बनाएं',
  'Custom headers' => 'कस्टम हेडर',
  'Edit webhook' => 'वेबहुक संपादित करें',
  'HTTP body' => 'HTTP बॉडी',
  'HTTP settings' => 'HTTP सेटिंग्स',
  'No custom headers defined' => 'कोई कस्टम हेडर परिभाषित नहीं',
  'No webhooks' => 'कोई वेबहुक नहीं',
  'Payload' => 'पेलोड',
  'Request Method' => 'अनुरोध विधि',
  'Trigger webhook' => 'वेबहुक ट्रिगर करें',
  'Update webhook' => 'वेबहुक अपडेट करें',
  'Webhook created!' => 'वेबहुक बनाया गया!',
  'Webhook finished' => 'वेबहुक समाप्त',
  'Webhook updated!' => 'वेबहुक अपडेट किया गया!',
  'Webhooks' => 'वेबहुक',
);