<?php return array (
  'All assets' => 'Todos los archivos',
  'Asset actions' => 'Acciones de archivo',
  'Asset file updated!' => '¡Archivo actualizado!',
  'Asset link copied!' => '¡Enlace de archivo copiado!',
  'Asset removed!' => '¡Archivo eliminado!',
  'Asset updated!' => '¡Archivo actualizado!',
  'Assets removed!' => '¡Archivos eliminados!',
  'Color copied!' => '¡Color copiado!',
  'Copy asset link' => 'Copiar enlace del archivo',
  'Edit asset' => 'Editar archivo',
  'Folder' => 'Carpeta',
  'Folder icon' => 'Icono de carpeta',
  'Folder name' => 'Nombre de la carpeta',
  'Folder name contains invalid characters' => 'El nombre de la carpeta contiene caracteres no válidos',
  'Folder name is required' => 'El nombre de la carpeta es obligatorio',
  'Folder removed!' => '¡Carpeta eliminada!',
  'Go to assets' => 'Ir a archivos',
  'Latest uploaded assets' => 'Últimos archivos subidos',
  'Mime' => 'Mime',
  'No asset selected' => 'Ningún archivo seleccionado',
  'No assets' => 'Sin archivos',
  'Parent folder' => 'Carpeta padre',
  'Select' => 'Seleccionar',
  'Upload asset' => 'Subir archivo',
  'Upload failed for:' => 'Carga fallida para:',
  'none' => 'ninguno',
);