<?php return [
    'Create file' => 'Crear archivo',
    'Create folder' => 'Crear carpeta',
    'Delete' => 'Eliminar',
    'Download' => 'Descargar',
    'Edit' => 'Editar',
    'Edit file' => 'Editar archivo',
    'Empty' => 'Vacío',
    'File actions' => 'Acciones de archivo',
    'File updated!' => '¡Archivo actualizado!',
    'File(s) deleted' => 'Archivo(s) eliminado(s)',
    'File(s) size exceeds max upload size limit!' => '¡El tamaño del archivo(s) excede el límite máximo de carga!',
    'Finder' => 'Explorador',
    'Folder actions' => 'Acciones de carpeta',
    'Item(s) deleted' => 'Elemento(s) eliminado(s)',
    'Link file' => 'Enlazar archivo',
    'Name' => 'Nombre',
    'No file linked' => 'Ningún archivo enlazado',
    'Readonly' => 'Solo lectura',
    'Rename' => 'Renombrar',
    'Reset' => 'Restablecer',
    'Select file' => 'Seleccionar archivo',
    'Settings' => 'Configuración',
    'Size' => 'Tamaño',
    'Updated' => 'Actualizado',
    'Upload failed!' => '¡Error al cargar!',
    'Upload file' => 'Cargar archivo',
];