<?php return array (
  'Choose suggestion' => 'Elegir sugerencia',
  'Create project' => 'Crear proyecto',
  'Edit project' => 'Editar proyecto',
  'Filtered keys' => 'Claves filtradas',
  'Key' => 'Clave',
  'Key actions' => 'Acciones de clave',
  'Key already exists!' => '¡La clave ya existe!',
  'Key editor' => 'Editor de claves',
  'Keys' => 'Claves',
  'Keys imported' => 'Claves importadas',
  'Lokalize' => 'Localizar',
  'No keys defined' => 'Sin claves definidas',
  'No project created yet' => 'Aún no se ha creado ningún proyecto',
  'No projects' => 'Sin proyectos',
  'Non visible' => 'No visible',
  'One' => 'Uno',
  'Please add some locales!' => '¡Por favor añade algunos idiomas!',
  'Project' => 'Proyecto',
  'Project created!' => '¡Proyecto creado!',
  'Project updated!' => '¡Proyecto actualizado!',
  'Save key' => 'Guardar clave',
  'Save project' => 'Guardar proyecto',
  'Target language' => 'Idioma de destino',
  'Text Translation' => 'Traducción de texto',
  'Translate' => 'Traducir',
  'Update project' => 'Actualizar proyecto',
);