<?php return [
    'Add event' => 'Agregar evento',
    'Add header' => 'Agregar encabezado',
    'Create webhook' => 'Crear webhook',
    'Custom headers' => 'Encabezados personalizados',
    'Delete' => 'Eliminar',
    'Edit' => 'Editar',
    'Edit webhook' => 'Editar webhook',
    'Events' => 'Eventos',
    'HTTP body' => 'Cuerpo HTTP',
    'HTTP settings' => 'Configuración HTTP',
    'Name' => 'Nombre',
    'No custom headers defined' => 'No se han definido encabezados personalizados',
    'No events defined' => 'No se han definido eventos',
    'No webhooks' => 'No hay webhooks',
    'Payload' => 'Carga',
    'Request Method' => 'Método de solicitud',
    'Settings' => 'Configuraciones',
    'Trigger webhook' => 'Activar webhook',
    'Update webhook' => 'Actualizar webhook',
    'Url' => 'URL',
    'Webhook created!' => '¡Webhook creado!',
    'Webhook triggered!' => '¡Webhook activado!',
    'Webhook updated!' => '¡Webhook actualizado!',
    'Webhooks' => 'Webhooks',
];