<?php return array (
  'Add header' => 'Añadir encabezado',
  'Calling webhook url' => 'Llamando URL del webhook',
  'Create webhook' => 'Crear webhook',
  'Custom headers' => 'Encabezados personalizados',
  'Edit webhook' => 'Editar webhook',
  'HTTP body' => 'Cuerpo HTTP',
  'HTTP settings' => 'Configuración HTTP',
  'No custom headers defined' => 'Sin encabezados personalizados definidos',
  'No webhooks' => 'Sin webhooks',
  'Payload' => 'Carga útil',
  'Request Method' => 'Método de solicitud',
  'Trigger webhook' => 'Disparar webhook',
  'Update webhook' => 'Actualizar webhook',
  'Webhook created!' => '¡Webhook creado!',
  'Webhook finished' => 'Webhook finalizado',
  'Webhook updated!' => '¡Webhook actualizado!',
  'Webhooks' => 'Webhooks',
);