<?php return array (
  'All assets' => 'Alle bestanden',
  'Asset actions' => 'Bestandsacties',
  'Asset file updated!' => 'Bestand bijgewerkt!',
  'Asset link copied!' => 'Bestandslink gekopieerd!',
  'Asset removed!' => 'Bestand verwijderd!',
  'Asset updated!' => 'Bestand bijgewerkt!',
  'Assets removed!' => 'Bestanden verwijderd!',
  'Color copied!' => 'Kleur gekopieerd!',
  'Copy asset link' => 'Kopieer bestandslink',
  'Edit asset' => 'Bestand bewerken',
  'Folder' => 'Map',
  'Folder icon' => 'Mapicoon',
  'Folder name' => 'Mapnaam',
  'Folder name contains invalid characters' => 'Mapnaam bevat ongeldige tekens',
  'Folder name is required' => 'Mapnaam is verplicht',
  'Folder removed!' => 'Map verwijderd!',
  'Go to assets' => 'Ga naar bestanden',
  'Latest uploaded assets' => 'Laatst geüploade bestanden',
  'Mime' => 'Mime',
  'No asset selected' => 'Geen bestand geselecteerd',
  'No assets' => 'Geen bestanden',
  'Parent folder' => 'Bovenliggende map',
  'Select' => 'Selecteren',
  'Upload asset' => 'Bestand uploaden',
  'Upload failed for:' => 'Uploaden mislukt voor:',
  'none' => 'geen',
);