<?php return array (
  'Add header' => 'Header toevoegen',
  'Calling webhook url' => 'Webhook-URL aanroepen',
  'Create webhook' => 'Webhook aanmaken',
  'Custom headers' => 'Aangepaste headers',
  'Edit webhook' => 'Webhook bewerken',
  'HTTP body' => 'HTTP-body',
  'HTTP settings' => 'HTTP-instellingen',
  'No custom headers defined' => 'Geen aangepaste headers gedefinieerd',
  'No webhooks' => 'Geen webhooks',
  'Payload' => 'Payload',
  'Request Method' => 'Verzoekmethode',
  'Trigger webhook' => 'Webhook activeren',
  'Update webhook' => 'Webhook bijwerken',
  'Webhook created!' => 'Webhook aangemaakt!',
  'Webhook finished' => 'Webhook voltooid',
  'Webhook updated!' => 'Webhook bijgewerkt!',
  'Webhooks' => 'Webhooks',
);