<?php return array (
  'All assets' => 'Todos os arquivos',
  'Asset actions' => 'Ações de arquivo',
  'Asset file updated!' => 'Arquivo atualizado!',
  'Asset link copied!' => 'Link do arquivo copiado!',
  'Asset removed!' => 'Arquivo removido!',
  'Asset updated!' => 'Arquivo atualizado!',
  'Assets removed!' => 'Arquivos removidos!',
  'Color copied!' => 'Cor copiada!',
  'Copy asset link' => 'Copiar link do arquivo',
  'Edit asset' => 'Editar arquivo',
  'Folder' => 'Pasta',
  'Folder icon' => 'Ícone da pasta',
  'Folder name' => 'Nome da pasta',
  'Folder name contains invalid characters' => 'O nome da pasta contém caracteres inválidos',
  'Folder name is required' => 'O nome da pasta é obrigatório',
  'Folder removed!' => 'Pasta removida!',
  'Go to assets' => 'Ir para arquivos',
  'Latest uploaded assets' => 'Últimos arquivos carregados',
  'Mime' => 'Mime',
  'No asset selected' => 'Nenhum arquivo selecionado',
  'No assets' => 'Sem arquivos',
  'Parent folder' => 'Pasta pai',
  'Select' => 'Selecionar',
  'Upload asset' => 'Carregar arquivo',
  'Upload failed for:' => 'Upload falhou para:',
  'none' => 'nenhum',
);