<?php return [
    'Create file' => 'Criar arquivo',
    'Create folder' => 'Criar pasta',
    'Delete' => 'Apagar',
    'Download' => 'Download',
    'Edit' => 'Editar',
    'Edit file' => 'Editar arquivo',
    'Empty' => 'Vazio',
    'File actions' => 'Ações de arquivo',
    'File updated!' => 'Arquivo atualizado!',
    'File(s) deleted' => 'Arquivo(s) apagado(s)',
    'File(s) size exceeds max upload size limit!' => 'O tamanho do(s) arquivo(s) excede o limite máximo de tamanho de upload!',
    'Finder' => 'Localizador',
    'Folder actions' => 'Ações de pasta',
    'Item(s) deleted' => 'Item eliminado',
    'Link file' => 'Linkar arquivo',
    'Name' => 'Nome',
    'No file linked' => 'Nenhuma arquivo linkado',
    'Readonly' => 'Somente leitura',
    'Rename' => 'Renomear',
    'Reset' => 'Reiniciar',
    'Select file' => 'Selecionar arquivo',
    'Settings' => 'Configurações',
    'Size' => 'Tamanho',
    'Updated' => 'Atualizado',
    'Upload failed!' => 'Erro ao carregar!',
    'Upload file' => 'Carregar arquivo',
];
