<?php return [
    'Add event' => 'Adicionar evento',
    'Add header' => 'Adicionar cabeçalho',
    'Create webhook' => 'Criar webhook',
    'Custom headers' => 'Cabeçalhos personalizados',
    'Delete' => 'Apagar',
    'Edit' => 'Editar',
    'Edit webhook' => 'Editar webhook',
    'Events' => 'Eventos',
    'HTTP body' => 'Corpo HTTP',
    'HTTP settings' => 'Configurações HTTP',
    'Name' => 'Nome',
    'No custom headers defined' => 'Nenhum cabeçalho personalizado definido',
    'No events defined' => 'Nenhum evento definido',
    'No webhooks' => 'Nenhum webhook',
    'Payload' => 'Payload',
    'Request Method' => 'Método de solicitação',
    'Settings' => 'Configurações',
    'Trigger webhook' => 'Ativar webhook',
    'Update webhook' => 'Atualizar webhook',
    'Url' => 'URL',
    'Webhook created!' => 'Webhook criado!',
    'Webhook triggered!' => 'Webhook ativado!',
    'Webhook updated!' => 'Webhook atualizado!',
    'Webhooks' => 'Webhooks',
];
