<?php return array (
  'Add header' => 'Adicionar cabeçalho',
  'Calling webhook url' => 'Chamando URL do webhook',
  'Create webhook' => 'Criar webhook',
  'Custom headers' => 'Cabeçalhos personalizados',
  'Edit webhook' => 'Editar webhook',
  'HTTP body' => 'Corpo HTTP',
  'HTTP settings' => 'Configurações HTTP',
  'No custom headers defined' => 'Sem cabeçalhos personalizados definidos',
  'No webhooks' => 'Sem webhooks',
  'Payload' => 'Carga útil',
  'Request Method' => 'Método de Solicitação',
  'Trigger webhook' => 'Acionar webhook',
  'Update webhook' => 'Atualizar webhook',
  'Webhook created!' => 'Webhook criado!',
  'Webhook finished' => 'Webhook finalizado',
  'Webhook updated!' => 'Webhook atualizado!',
  'Webhooks' => 'Webhooks',
);