<?php return array (
  'All assets' => 'Semua aset',
  'Asset actions' => 'Tindakan aset',
  'Asset file updated!' => 'File aset diperbarui!',
  'Asset link copied!' => 'Tautan aset disalin!',
  'Asset removed!' => 'Aset dihapus!',
  'Asset updated!' => 'Aset diperbarui!',
  'Assets removed!' => 'Aset dihapus!',
  'Color copied!' => 'Warna disalin!',
  'Copy asset link' => 'Salin tautan aset',
  'Edit asset' => 'Edit aset',
  'Folder' => 'Folder',
  'Folder icon' => 'Ikon folder',
  'Folder name' => 'Nama folder',
  'Folder name contains invalid characters' => 'Nama folder mengandung karakter tidak valid',
  'Folder name is required' => 'Nama folder diperlukan',
  'Folder removed!' => 'Folder dihapus!',
  'Go to assets' => 'Pergi ke aset',
  'Latest uploaded assets' => 'Aset yang baru diunggah',
  'Mime' => 'Mime',
  'No asset selected' => 'Tidak ada aset yang dipilih',
  'No assets' => 'Tidak ada aset',
  'Parent folder' => 'Folder induk',
  'Select' => 'Pilih',
  'Upload asset' => 'Unggah aset',
  'Upload failed for:' => 'Unggah gagal untuk:',
  'none' => 'tidak ada',
);