<?php return [
  'Create file' => 'Buat file',
  'Create folder' => 'Buat folder',
  'Delete' => 'Hapus',
  'Download' => 'Unduh',
  'Edit' => 'Edit',
  'Edit file' => 'Edit file',
  'Empty' => 'Kosong',
  'File actions' => 'Aksi file',
  'File updated!' => 'File diperbarui!',
  'File(s) deleted' => 'File dihapus',
  'File(s) size exceeds max upload size limit!' => 'Ukuran file melebihi batas ukuran unggahan maksimum!',
  'Finder' => 'Finder',
  'Folder actions' => 'Aksi folder',
  'Item(s) deleted' => 'Item dihapus',
  'Link file' => 'Tautkan file',
  'Name' => 'Nama',
  'No file linked' => 'Tidak ada file yang ditautkan',
  'Readonly' => 'Readonly',
  'Rename' => 'Ubah nama',
  'Reset' => 'Atur ulang',
  'Select file' => 'Pilih file',
  'Settings' => 'Pengaturan',
  'Size' => 'Ukuran',
  'Updated' => 'Diperbarui',
  'Upload failed!' => 'Gagal diunggah!',
  'Upload file' => 'Unggah file',
];
