<?php return array (
  'Choose suggestion' => 'Pilih saran',
  'Create project' => 'Buat proyek',
  'Edit project' => 'Edit proyek',
  'Filtered keys' => 'Kunci difilter',
  'Key' => 'Kunci',
  'Key actions' => 'Tindakan kunci',
  'Key already exists!' => 'Kunci sudah ada!',
  'Key editor' => 'Editor kunci',
  'Keys' => 'Kunci',
  'Keys imported' => 'Kunci diimpor',
  'Lokalize' => 'Lokalisasi',
  'No keys defined' => 'Tidak ada kunci didefinisikan',
  'No project created yet' => 'Belum ada proyek dibuat',
  'No projects' => 'Tidak ada proyek',
  'Non visible' => 'Tidak terlihat',
  'One' => 'Satu',
  'Please add some locales!' => 'Harap tambahkan beberapa lokal!',
  'Project' => 'Proyek',
  'Project created!' => 'Proyek dibuat!',
  'Project updated!' => 'Proyek diperbarui!',
  'Save key' => 'Simpan kunci',
  'Save project' => 'Simpan proyek',
  'Target language' => 'Bahasa target',
  'Text Translation' => 'Terjemahan Teks',
  'Translate' => 'Terjemahkan',
  'Update project' => 'Perbarui proyek',
);