<?php return array (
  'Add header' => 'Tambah header',
  'Calling webhook url' => 'Memanggil URL webhook',
  'Create webhook' => 'Buat webhook',
  'Custom headers' => 'Header kustom',
  'Edit webhook' => 'Edit webhook',
  'HTTP body' => 'Badan HTTP',
  'HTTP settings' => 'Pengaturan HTTP',
  'No custom headers defined' => 'Tidak ada header kustom didefinisikan',
  'No webhooks' => 'Tidak ada webhook',
  'Payload' => 'Payload',
  'Request Method' => 'Metode Permintaan',
  'Trigger webhook' => 'Picu webhook',
  'Update webhook' => 'Perbarui webhook',
  'Webhook created!' => 'Webhook dibuat!',
  'Webhook finished' => 'Webhook selesai',
  'Webhook updated!' => 'Webhook diperbarui!',
  'Webhooks' => 'Webhooks',
);