<?php return [
  'Add event' => 'Tambah event',
  'Add header' => 'Tambah header',
  'Create webhook' => 'Buat webhook',
  'Custom headers' => 'Header kustom',
  'Delete' => 'Hapus',
  'Edit' => 'Edit',
  'Edit webhook' => 'Edit webhook',
  'Events' => 'Event',
  'HTTP body' => 'Bodi HTTP',
  'HTTP settings' => 'Pengaturan HTTP',
  'Name' => 'Nama',
  'No custom headers defined' => 'Tidak ada header kustom yang didefinisikan',
  'No events defined' => 'Tidak ada event yang didefinisikan',
  'No webhooks' => 'Tidak ada webhook',
  'Payload' => 'Payload',
  'Request Method' => 'Metode request',
  'Settings' => 'Pengaturan',
  'Trigger webhook' => 'Picu webhook',
  'Update webhook' => 'Perbarui webhook',
  'Url' => 'URL',
  'Webhook created!' => 'Webhook dibuat!',
  'Webhook triggered!' => 'Webhook dipicu!',
  'Webhook updated!' => 'Webhook diperbarui!',
  'Webhooks' => 'Webhooks',
];
