<?php return array (
  'All assets' => '모든 자산',
  'Asset actions' => '자산 작업',
  'Asset file updated!' => '자산 파일이 업데이트되었습니다!',
  'Asset link copied!' => '자산 링크가 복사되었습니다!',
  'Asset removed!' => '자산이 제거되었습니다!',
  'Asset updated!' => '자산이 업데이트되었습니다!',
  'Assets removed!' => '자산이 제거되었습니다!',
  'Color copied!' => '색상이 복사되었습니다!',
  'Copy asset link' => '자산 링크 복사',
  'Edit asset' => '자산 편집',
  'Folder' => '폴더',
  'Folder icon' => '폴더 아이콘',
  'Folder name' => '폴더 이름',
  'Folder name contains invalid characters' => '폴더 이름에 유효하지 않은 문자가 포함되어 있습니다',
  'Folder name is required' => '폴더 이름은 필수입니다',
  'Folder removed!' => '폴더가 제거되었습니다!',
  'Go to assets' => '자산으로 이동',
  'Latest uploaded assets' => '최근 업로드된 자산',
  'Mime' => 'MIME',
  'No asset selected' => '선택된 자산 없음',
  'No assets' => '자산 없음',
  'Parent folder' => '상위 폴더',
  'Select' => '선택',
  'Upload asset' => '자산 업로드',
  'Upload failed for:' => '업로드 실패:',
  'none' => '없음',
);