<?php return array (
  'Choose suggestion' => '제안 선택',
  'Create project' => '프로젝트 생성',
  'Edit project' => '프로젝트 편집',
  'Filtered keys' => '필터링된 키',
  'Key' => '키',
  'Key actions' => '키 작업',
  'Key already exists!' => '키가 이미 존재합니다!',
  'Key editor' => '키 에디터',
  'Keys' => '키',
  'Keys imported' => '키가 가져와졌습니다',
  'Lokalize' => '로컬라이즈',
  'No keys defined' => '정의된 키 없음',
  'No project created yet' => '아직 생성된 프로젝트 없음',
  'No projects' => '프로젝트 없음',
  'Non visible' => '보이지 않음',
  'One' => '하나',
  'Please add some locales!' => '로케일을 추가하세요!',
  'Project' => '프로젝트',
  'Project created!' => '프로젝트가 생성되었습니다!',
  'Project updated!' => '프로젝트가 업데이트되었습니다!',
  'Save key' => '키 저장',
  'Save project' => '프로젝트 저장',
  'Target language' => '대상 언어',
  'Text Translation' => '텍스트 번역',
  'Translate' => '번역',
  'Update project' => '프로젝트 업데이트',
);