<?php return array (
  'Add header' => '헤더 추가',
  'Calling webhook url' => '웹훅 URL 호출 중',
  'Create webhook' => '웹훅 생성',
  'Custom headers' => '커스텀 헤더',
  'Edit webhook' => '웹훅 편집',
  'HTTP body' => 'HTTP 본문',
  'HTTP settings' => 'HTTP 설정',
  'No custom headers defined' => '정의된 커스텀 헤더 없음',
  'No webhooks' => '웹훅 없음',
  'Payload' => '페이로드',
  'Request Method' => '요청 메서드',
  'Trigger webhook' => '웹훅 트리거',
  'Update webhook' => '웹훅 업데이트',
  'Webhook created!' => '웹훅이 생성되었습니다!',
  'Webhook finished' => '웹훅 완료',
  'Webhook updated!' => '웹훅이 업데이트되었습니다!',
  'Webhooks' => '웹훅',
);