<?php return array (
  'All assets' => 'Všetky súbory',
  'Asset actions' => 'Akcie súboru',
  'Asset file updated!' => 'Súbor aktualizovaný!',
  'Asset link copied!' => 'Odkaz na súbor skopírovaný!',
  'Asset removed!' => 'Súbor odstránený!',
  'Asset updated!' => 'Súbor aktualizovaný!',
  'Assets removed!' => 'Súbory odstránené!',
  'Color copied!' => 'Farba skopírovaná!',
  'Copy asset link' => 'Kopírovať odkaz na súbor',
  'Edit asset' => 'Upraviť súbor',
  'Folder' => 'Priečinok',
  'Folder icon' => 'Ikona priečinka',
  'Folder name' => 'Názov priečinka',
  'Folder name contains invalid characters' => 'Názov priečinka obsahuje neplatné znaky',
  'Folder name is required' => 'Názov priečinka je povinný',
  'Folder removed!' => 'Priečinok odstránený!',
  'Go to assets' => 'Prejsť na súbory',
  'Latest uploaded assets' => 'Naposledy nahrané súbory',
  'Mime' => 'Mime',
  'No asset selected' => 'Nebol vybraný žiadny súbor',
  'No assets' => 'Žiadne súbory',
  'Parent folder' => 'Nadradený priečinok',
  'Select' => 'Vybrať',
  'Upload asset' => 'Nahrať súbor',
  'Upload failed for:' => 'Nahrávanie zlyhalo pre:',
  'none' => 'žiadne',
);