<?php return array (
  'Choose suggestion' => 'Vybrať návrh',
  'Create project' => 'Vytvoriť projekt',
  'Edit project' => 'Upraviť projekt',
  'Filtered keys' => 'Filtrované kľúče',
  'Key' => 'Kľúč',
  'Key actions' => 'Akcie kľúča',
  'Key already exists!' => 'Kľúč už existuje!',
  'Key editor' => 'Editor kľúčov',
  'Keys' => 'Kľúče',
  'Keys imported' => 'Kľúče importované',
  'Lokalize' => 'Lokalizovať',
  'No keys defined' => 'Nie sú definované žiadne kľúče',
  'No project created yet' => 'Zatiaľ nebol vytvorený žiadny projekt',
  'No projects' => 'Žiadne projekty',
  'Non visible' => 'Neviditeľné',
  'One' => 'Jeden',
  'Please add some locales!' => 'Prosím pridajte nejaké jazyky!',
  'Project' => 'Projekt',
  'Project created!' => 'Projekt vytvorený!',
  'Project updated!' => 'Projekt aktualizovaný!',
  'Save key' => 'Uložiť kľúč',
  'Save project' => 'Uložiť projekt',
  'Target language' => 'Cieľový jazyk',
  'Text Translation' => 'Preklad Textu',
  'Translate' => 'Preložiť',
  'Update project' => 'Aktualizovať projekt',
);