<?php return [
  'Add event' => 'Pridať udalosť',
  'Add header' => 'Pridať hlavičku',
  'Cancel' => 'Zrušiť',
  'Close' => 'Zatvoriť',
  'Create webhook' => 'Vytvoriť webhook',
  'Custom headers' => 'Vlastné hlavičky',
  'Delete' => 'Vymazať',
  'Edit' => 'Upraviť',
  'Edit webhook' => 'Upraviť webhook',
  'Events' => 'Udalosti',
  'HTTP body' => 'HTTP telo',
  'HTTP settings' => 'HTTP nastavenia',
  'Name' => 'Meno',
  'No custom headers defined' => 'Nie sú definované žiadne vlastné hlavičky',
  'No events defined' => 'Nie sú definované žiadne udalosti',
  'No webhooks' => 'Žiadne webhooks',
  'Payload' => 'Náklad',
  'Request Method' => 'Metóda požiadavky',
  'Settings' => 'Nastavenia',
  'Trigger webhook' => 'Spustiť webhook',
  'Update webhook' => 'Aktualizovať webhook',
  'Url' => 'URL',
  'Webhook created!' => 'Webhook vytvorený!',
  'Webhook triggered!' => 'Webhook spustený!',
  'Webhook updated!' => 'Webhook aktualizovaný!',
  'Webhooks' => 'Webhooks',
];