<?php return array (
  'Add header' => 'Pridať hlavičku',
  'Calling webhook url' => 'Volanie URL webhooku',
  'Create webhook' => 'Vytvoriť webhook',
  'Custom headers' => 'Vlastné hlavičky',
  'Edit webhook' => 'Upraviť webhook',
  'HTTP body' => 'HTTP telo',
  'HTTP settings' => 'HTTP nastavenia',
  'No custom headers defined' => 'Nie sú definované žiadne vlastné hlavičky',
  'No webhooks' => 'Žiadne webhooky',
  'Payload' => 'Payload',
  'Request Method' => 'Metóda Požiadavky',
  'Trigger webhook' => 'Spustiť webhook',
  'Update webhook' => 'Aktualizovať webhook',
  'Webhook created!' => 'Webhook vytvorený!',
  'Webhook finished' => 'Webhook dokončený',
  'Webhook updated!' => 'Webhook aktualizovaný!',
  'Webhooks' => 'Webhooky',
);