<?php return array (
  'All assets' => 'Alle filer',
  'Asset actions' => 'Filhandlinger',
  'Asset file updated!' => 'Fil opdateret!',
  'Asset link copied!' => 'Fillink kopieret!',
  'Asset removed!' => 'Fil fjernet!',
  'Asset updated!' => 'Fil opdateret!',
  'Assets removed!' => 'Filer fjernet!',
  'Color copied!' => 'Farve kopieret!',
  'Copy asset link' => 'Kopier fillink',
  'Edit asset' => 'Rediger fil',
  'Folder' => 'Mappe',
  'Folder icon' => 'Mappeikon',
  'Folder name' => 'Mappenavn',
  'Folder name contains invalid characters' => 'Mappenavnet indeholder ugyldige tegn',
  'Folder name is required' => 'Mappenavn er påkrævet',
  'Folder removed!' => 'Mappe fjernet!',
  'Go to assets' => 'Gå til filer',
  'Latest uploaded assets' => 'Senest uploadede filer',
  'Mime' => 'Mime',
  'No asset selected' => 'Ingen fil valgt',
  'No assets' => 'Ingen filer',
  'Parent folder' => 'Overordnet mappe',
  'Select' => 'Vælg',
  'Upload asset' => 'Upload fil',
  'Upload failed for:' => 'Upload mislykkedes for:',
  'none' => 'ingen',
);