<?php return array (
  'Choose suggestion' => 'Vælg forslag',
  'Create project' => 'Opret projekt',
  'Edit project' => 'Rediger projekt',
  'Filtered keys' => 'Filtrerede nøgler',
  'Key' => 'Nøgle',
  'Key actions' => 'Nøglehandlinger',
  'Key already exists!' => 'Nøgle eksisterer allerede!',
  'Key editor' => 'Nøgleeditor',
  'Keys' => 'Nøgler',
  'Keys imported' => 'Nøgler importeret',
  'Lokalize' => 'Lokalize',
  'No keys defined' => 'Ingen nøgler defineret',
  'No project created yet' => 'Intet projekt oprettet endnu',
  'No projects' => 'Ingen projekter',
  'Non visible' => 'Ikke synlig',
  'One' => 'En',
  'Please add some locales!' => 'Tilføj venligst nogle sprog!',
  'Project' => 'Projekt',
  'Project created!' => 'Projekt oprettet!',
  'Project updated!' => 'Projekt opdateret!',
  'Save key' => 'Gem nøgle',
  'Save project' => 'Gem projekt',
  'Target language' => 'Målsprog',
  'Text Translation' => 'Tekstoversættelse',
  'Translate' => 'Oversæt',
  'Update project' => 'Opdater projekt',
);