<?php return array (
  'Add header' => 'Tilføj overskrift',
  'Calling webhook url' => 'Kalder webhook-url',
  'Create webhook' => 'Opret webhook',
  'Custom headers' => 'Tilpassede overskrifter',
  'Edit webhook' => 'Rediger webhook',
  'HTTP body' => 'HTTP-krop',
  'HTTP settings' => 'HTTP-indstillinger',
  'No custom headers defined' => 'Ingen tilpassede overskrifter defineret',
  'No webhooks' => 'Ingen webhooks',
  'Payload' => 'Payload',
  'Request Method' => 'Forespørgselsmetode',
  'Trigger webhook' => 'Udløs webhook',
  'Update webhook' => 'Opdater webhook',
  'Webhook created!' => 'Webhook oprettet!',
  'Webhook finished' => 'Webhook afsluttet',
  'Webhook updated!' => 'Webhook opdateret!',
  'Webhooks' => 'Webhooks',
);