<?php return array (
  'All assets' => 'Todos os ficheiros',
  'Asset actions' => 'Ações de ficheiro',
  'Asset file updated!' => 'Ficheiro atualizado!',
  'Asset link copied!' => 'Ligação do ficheiro copiada!',
  'Asset removed!' => 'Ficheiro removido!',
  'Asset updated!' => 'Ficheiro atualizado!',
  'Assets removed!' => 'Ficheiros removidos!',
  'Color copied!' => 'Cor copiada!',
  'Copy asset link' => 'Copiar ligação do ficheiro',
  'Edit asset' => 'Editar ficheiro',
  'Folder' => 'Pasta',
  'Folder icon' => 'Ícone da pasta',
  'Folder name' => 'Nome da pasta',
  'Folder name contains invalid characters' => 'O nome da pasta contém caracteres inválidos',
  'Folder name is required' => 'O nome da pasta é obrigatório',
  'Folder removed!' => 'Pasta removida!',
  'Go to assets' => 'Ir para ficheiros',
  'Latest uploaded assets' => 'Últimos ficheiros carregados',
  'Mime' => 'Mime',
  'No asset selected' => 'Nenhum ficheiro selecionado',
  'No assets' => 'Sem ficheiros',
  'Parent folder' => 'Pasta ascendente',
  'Select' => 'Selecionar',
  'Upload asset' => 'Carregar ficheiro',
  'Upload failed for:' => 'Carregamento falhou para:',
  'none' => 'nenhum',
);