<?php return array (
  'Choose suggestion' => 'Escolher sugestão',
  'Create project' => 'Criar projeto',
  'Edit project' => 'Editar projeto',
  'Filtered keys' => 'Chaves filtradas',
  'Key' => 'Chave',
  'Key actions' => 'Ações de chave',
  'Key already exists!' => 'A chave já existe!',
  'Key editor' => 'Editor de Chaves',
  'Keys' => 'Chaves',
  'Keys imported' => 'Chaves importadas',
  'Lokalize' => 'Lokalize',
  'No keys defined' => 'Nenhuma chave definida',
  'No project created yet' => 'Ainda não foi criado nenhum projeto',
  'No projects' => 'Sem projetos',
  'Non visible' => 'Não visível',
  'One' => 'Um',
  'Please add some locales!' => 'Por favor, adicione algumas localidades!',
  'Project' => 'Projeto',
  'Project created!' => 'Projeto criado!',
  'Project updated!' => 'Projeto atualizado!',
  'Save key' => 'Guardar chave',
  'Save project' => 'Guardar projeto',
  'Target language' => 'Idioma de destino',
  'Text Translation' => 'Tradução de Texto',
  'Translate' => 'Traduzir',
  'Update project' => 'Atualizar projeto',
);