<?php return array (
  'Add header' => 'Adicionar cabeçalho',
  'Calling webhook url' => 'A chamar URL do webhook',
  'Create webhook' => 'Criar webhook',
  'Custom headers' => 'Cabeçalhos personalizados',
  'Edit webhook' => 'Editar webhook',
  'HTTP body' => 'Corpo HTTP',
  'HTTP settings' => 'Definições HTTP',
  'No custom headers defined' => 'Nenhum cabeçalho personalizado definido',
  'No webhooks' => 'Sem webhooks',
  'Payload' => 'Carga útil',
  'Request Method' => 'Método de Pedido',
  'Trigger webhook' => 'Despoletar webhook',
  'Update webhook' => 'Atualizar webhook',
  'Webhook created!' => 'Webhook criado!',
  'Webhook finished' => 'Webhook terminado',
  'Webhook updated!' => 'Webhook atualizado!',
  'Webhooks' => 'Webhooks',
);