<?php return array (
  'All assets' => 'همه فایل‌ها',
  'Asset actions' => 'عملیات فایل',
  'Asset file updated!' => 'فایل بروزرسانی شد!',
  'Asset link copied!' => 'لینک فایل کپی شد!',
  'Asset removed!' => 'فایل حذف شد!',
  'Asset updated!' => 'فایل بروزرسانی شد!',
  'Assets removed!' => 'فایل‌ها حذف شدند!',
  'Color copied!' => 'رنگ کپی شد!',
  'Copy asset link' => 'کپی لینک فایل',
  'Edit asset' => 'ویرایش فایل',
  'Folder' => 'پوشه',
  'Folder icon' => 'آیکون پوشه',
  'Folder name' => 'نام پوشه',
  'Folder name contains invalid characters' => 'نام پوشه حاوی کاراکترهای نامعتبر است',
  'Folder name is required' => 'نام پوشه الزامی است',
  'Folder removed!' => 'پوشه حذف شد!',
  'Go to assets' => 'برو به فایل‌ها',
  'Latest uploaded assets' => 'آخرین فایل‌های آپلود شده',
  'Mime' => 'Mime',
  'No asset selected' => 'هیچ فایلی انتخاب نشده است',
  'No assets' => 'هیچ فایلی وجود ندارد',
  'Parent folder' => 'پوشه والد',
  'Select' => 'انتخاب',
  'Upload asset' => 'آپلود فایل',
  'Upload failed for:' => 'آپلود ناموفق برای:',
  'none' => 'هیچ',
);