<?php return [
  'Close' => 'بستن',
  'Create file' => 'ایجاد فایل',
  'Create folder' => 'ایجاد پوشه',
  'Delete' => 'حذف',
  'Download' => 'دانلود',
  'Edit' => 'ویرایش',
  'Edit file' => 'ویرایش فایل',
  'Empty' => 'خالی',
  'File actions' => 'عملیات فایل',
  'File updated!' => 'فایل به‌روزرسانی شد!',
  'File(s) deleted' => 'فایل‌(ها) حذف شدند',
  'File(s) size exceeds max upload size limit!' => 'حجم فایل(ها) از حد مجاز بیشتر است!',
  'Finder' => 'مدیریت فایل',
  'Folder actions' => 'عملیات پوشه',
  'Item(s) deleted' => 'آیتم‌(ها) حذف شدند',
  'Name' => 'نام',
  'Readonly' => 'فقط خواندنی',
  'Rename' => 'تغییر نام',
  'Save' => 'ذخیره',
  'Settings' => 'تنظیمات',
  'Size' => 'حجم',
  'Updated' => 'به‌روزرسانی شد',
  'Upload failed!' => 'آپلود ناموفق بود!',
  'Upload file' => 'آپلود فایل',
];