<?php return array (
  'Add header' => 'افزودن هدر',
  'Calling webhook url' => 'فراخوانی URL وب‌هوک',
  'Create webhook' => 'ایجاد وب‌هوک',
  'Custom headers' => 'هدرهای سفارشی',
  'Edit webhook' => 'ویرایش وب‌هوک',
  'HTTP body' => 'بدنه HTTP',
  'HTTP settings' => 'تنظیمات HTTP',
  'No custom headers defined' => 'هدر سفارشی تعریف نشده است',
  'No webhooks' => 'هیچ وب‌هوکی وجود ندارد',
  'Payload' => 'Payload',
  'Request Method' => 'روش درخواست',
  'Trigger webhook' => 'اجرای وب‌هوک',
  'Update webhook' => 'بروزرسانی وب‌هوک',
  'Webhook created!' => 'وب‌هوک ایجاد شد!',
  'Webhook finished' => 'وب‌هوک تمام شد',
  'Webhook updated!' => 'وب‌هوک بروزرسانی شد!',
  'Webhooks' => 'وب‌هوک‌ها',
);