<?php return array (
  'All assets' => '所有資產',
  'Asset actions' => '資產動作',
  'Asset file updated!' => '資產檔案已更新！',
  'Asset link copied!' => '資產連結已複製！',
  'Asset removed!' => '資產已移除！',
  'Asset updated!' => '資產已更新！',
  'Assets removed!' => '資產已移除！',
  'Color copied!' => '顏色已複製！',
  'Copy asset link' => '複製資產連結',
  'Edit asset' => '編輯資產',
  'Folder' => '資料夾',
  'Folder icon' => '資料夾圖示',
  'Folder name' => '資料夾名稱',
  'Folder name contains invalid characters' => '資料夾名稱包含無效字元',
  'Folder name is required' => '資料夾名稱為必填',
  'Folder removed!' => '資料夾已移除！',
  'Go to assets' => '前往資產',
  'Latest uploaded assets' => '最新上傳的資產',
  'Mime' => 'Mime',
  'No asset selected' => '未選取資產',
  'No assets' => '沒有資產',
  'Parent folder' => '上層資料夾',
  'Select' => '選取',
  'Upload asset' => '上傳資產',
  'Upload failed for:' => '上傳失敗：',
  'none' => '無',
);