<?php return array (
  'Choose suggestion' => '選擇建議',
  'Create project' => '建立專案',
  'Edit project' => '編輯專案',
  'Filtered keys' => '已篩選金鑰',
  'Key' => '金鑰',
  'Key actions' => '金鑰動作',
  'Key already exists!' => '金鑰已存在！',
  'Key editor' => '金鑰編輯器',
  'Keys' => '金鑰',
  'Keys imported' => '金鑰已匯入',
  'Lokalize' => 'Lokalize',
  'No keys defined' => '未定義金鑰',
  'No project created yet' => '尚未建立專案',
  'No projects' => '沒有專案',
  'Non visible' => '不可見',
  'One' => '一',
  'Please add some locales!' => '請新增一些語言！',
  'Project' => '專案',
  'Project created!' => '專案已建立！',
  'Project updated!' => '專案已更新！',
  'Save key' => '儲存金鑰',
  'Save project' => '儲存專案',
  'Target language' => '目標語言',
  'Text Translation' => '文字翻譯',
  'Translate' => '翻譯',
  'Update project' => '更新專案',
);