<?php return array (
  'Add header' => '新增標頭',
  'Calling webhook url' => '呼叫 Webhook URL',
  'Create webhook' => '建立 Webhook',
  'Custom headers' => '自訂標頭',
  'Edit webhook' => '編輯 Webhook',
  'HTTP body' => 'HTTP 本文',
  'HTTP settings' => 'HTTP 設定',
  'No custom headers defined' => '未定義自訂標頭',
  'No webhooks' => '沒有 Webhook',
  'Payload' => '負載',
  'Request Method' => '請求方法',
  'Trigger webhook' => '觸發 Webhook',
  'Update webhook' => '更新 Webhook',
  'Webhook created!' => 'Webhook 已建立！',
  'Webhook finished' => 'Webhook 已完成',
  'Webhook updated!' => 'Webhook 已更新！',
  'Webhooks' => 'Webhook',
);