<?php return array (
  'All assets' => 'Tous les fichiers',
  'Asset actions' => 'Actions sur le fichier',
  'Asset file updated!' => 'Fichier mis à jour !',
  'Asset link copied!' => 'Lien du fichier copié !',
  'Asset removed!' => 'Fichier supprimé !',
  'Asset updated!' => 'Fichier mis à jour !',
  'Assets removed!' => 'Fichiers supprimés !',
  'Color copied!' => 'Couleur copiée !',
  'Copy asset link' => 'Copier le lien du fichier',
  'Edit asset' => 'Modifier le fichier',
  'Folder' => 'Dossier',
  'Folder icon' => 'Icône du dossier',
  'Folder name' => 'Nom du dossier',
  'Folder name contains invalid characters' => 'Le nom du dossier contient des caractères invalides',
  'Folder name is required' => 'Le nom du dossier est requis',
  'Folder removed!' => 'Dossier supprimé !',
  'Go to assets' => 'Aller aux fichiers',
  'Latest uploaded assets' => 'Derniers fichiers téléchargés',
  'Mime' => 'Mime',
  'No asset selected' => 'Aucun fichier sélectionné',
  'No assets' => 'Aucun fichier',
  'Parent folder' => 'Dossier parent',
  'Select' => 'Sélectionner',
  'Upload asset' => 'Télécharger un fichier',
  'Upload failed for:' => 'Échec du téléchargement pour :',
  'none' => 'aucun',
);