<?php return array (
  'Choose suggestion' => 'Choisir une suggestion',
  'Create project' => 'Créer un projet',
  'Edit project' => 'Modifier le projet',
  'Filtered keys' => 'Clés filtrées',
  'Key' => 'Clé',
  'Key actions' => 'Actions sur la clé',
  'Key already exists!' => 'La clé existe déjà !',
  'Key editor' => 'Éditeur de clé',
  'Keys' => 'Clés',
  'Keys imported' => 'Clés importées',
  'Lokalize' => 'Localiser',
  'No keys defined' => 'Aucune clé définie',
  'No project created yet' => 'Aucun projet créé pour le moment',
  'No projects' => 'Aucun projet',
  'Non visible' => 'Non visible',
  'One' => 'Un',
  'Please add some locales!' => 'Veuillez ajouter des langues !',
  'Project' => 'Projet',
  'Project created!' => 'Projet créé !',
  'Project updated!' => 'Projet mis à jour !',
  'Save key' => 'Enregistrer la clé',
  'Save project' => 'Enregistrer le projet',
  'Target language' => 'Langue cible',
  'Text Translation' => 'Traduction de texte',
  'Translate' => 'Traduire',
  'Update project' => 'Mettre à jour le projet',
);