<?php return array (
  'Add header' => 'Ajouter un en-tête',
  'Calling webhook url' => 'Appel de l\'URL du webhook',
  'Create webhook' => 'Créer un webhook',
  'Custom headers' => 'En-têtes personnalisés',
  'Edit webhook' => 'Modifier le webhook',
  'HTTP body' => 'Corps HTTP',
  'HTTP settings' => 'Paramètres HTTP',
  'No custom headers defined' => 'Aucun en-tête personnalisé défini',
  'No webhooks' => 'Aucun webhook',
  'Payload' => 'Charge utile',
  'Request Method' => 'Méthode de requête',
  'Trigger webhook' => 'Déclencher le webhook',
  'Update webhook' => 'Mettre à jour le webhook',
  'Webhook created!' => 'Webhook créé !',
  'Webhook finished' => 'Webhook terminé',
  'Webhook updated!' => 'Webhook mis à jour !',
  'Webhooks' => 'Webhooks',
);