<?php return array (
  'All assets' => 'Alla filer',
  'Asset actions' => 'Filåtgärder',
  'Asset file updated!' => 'Fil uppdaterad!',
  'Asset link copied!' => 'Fillänk kopierad!',
  'Asset removed!' => 'Fil borttagen!',
  'Asset updated!' => 'Fil uppdaterad!',
  'Assets removed!' => 'Filer borttagna!',
  'Color copied!' => 'Färg kopierad!',
  'Copy asset link' => 'Kopiera fillänk',
  'Edit asset' => 'Redigera fil',
  'Folder' => 'Mapp',
  'Folder icon' => 'Mappikon',
  'Folder name' => 'Mappnamn',
  'Folder name contains invalid characters' => 'Mappnamnet innehåller ogiltiga tecken',
  'Folder name is required' => 'Mappnamn krävs',
  'Folder removed!' => 'Mapp borttagen!',
  'Go to assets' => 'Gå till filer',
  'Latest uploaded assets' => 'Senast uppladdade filer',
  'Mime' => 'Mime',
  'No asset selected' => 'Ingen fil vald',
  'No assets' => 'Inga filer',
  'Parent folder' => 'Överordnad mapp',
  'Select' => 'Välj',
  'Upload asset' => 'Ladda upp fil',
  'Upload failed for:' => 'Uppladdning misslyckades för:',
  'none' => 'ingen',
);