<?php return array (
  'Choose suggestion' => 'Välj förslag',
  'Create project' => 'Skapa projekt',
  'Edit project' => 'Redigera projekt',
  'Filtered keys' => 'Filtrerade nycklar',
  'Key' => 'Nyckel',
  'Key actions' => 'Nyckelåtgärder',
  'Key already exists!' => 'Nyckel finns redan!',
  'Key editor' => 'Nyckelredigerare',
  'Keys' => 'Nycklar',
  'Keys imported' => 'Nycklar importerade',
  'Lokalize' => 'Lokalizera',
  'No keys defined' => 'Inga nycklar definierade',
  'No project created yet' => 'Inget projekt skapat ännu',
  'No projects' => 'Inga projekt',
  'Non visible' => 'Ej synlig',
  'One' => 'En',
  'Please add some locales!' => 'Lägg till några språk!',
  'Project' => 'Projekt',
  'Project created!' => 'Projekt skapat!',
  'Project updated!' => 'Projekt uppdaterat!',
  'Save key' => 'Spara nyckel',
  'Save project' => 'Spara projekt',
  'Target language' => 'Målspråk',
  'Text Translation' => 'Textöversättning',
  'Translate' => 'Översätt',
  'Update project' => 'Uppdatera projekt',
);