<?php return array (
  'Add header' => 'Lägg till rubrik',
  'Calling webhook url' => 'Anropar webhook-URL',
  'Create webhook' => 'Skapa webhook',
  'Custom headers' => 'Anpassade rubriker',
  'Edit webhook' => 'Redigera webhook',
  'HTTP body' => 'HTTP-kropp',
  'HTTP settings' => 'HTTP-inställningar',
  'No custom headers defined' => 'Inga anpassade rubriker definierade',
  'No webhooks' => 'Inga webhooks',
  'Payload' => 'Payload',
  'Request Method' => 'Begäran Metod',
  'Trigger webhook' => 'Utlös webhook',
  'Update webhook' => 'Uppdatera webhook',
  'Webhook created!' => 'Webhook skapad!',
  'Webhook finished' => 'Webhook klar',
  'Webhook updated!' => 'Webhook uppdaterad!',
  'Webhooks' => 'Webhooks',
);