<?php return array (
  'All assets' => 'すべてのファイル',
  'Asset actions' => 'ファイル操作',
  'Asset file updated!' => 'ファイルを更新しました！',
  'Asset link copied!' => 'ファイルリンクをコピーしました！',
  'Asset removed!' => 'ファイルを削除しました！',
  'Asset updated!' => 'ファイルを更新しました！',
  'Assets removed!' => 'ファイルを削除しました！',
  'Color copied!' => '色をコピーしました！',
  'Copy asset link' => 'ファイルリンクをコピー',
  'Edit asset' => 'ファイルを編集',
  'Folder' => 'フォルダ',
  'Folder icon' => 'フォルダアイコン',
  'Folder name' => 'フォルダ名',
  'Folder name contains invalid characters' => 'フォルダ名に無効な文字が含まれています',
  'Folder name is required' => 'フォルダ名は必須です',
  'Folder removed!' => 'フォルダを削除しました！',
  'Go to assets' => 'ファイルへ移動',
  'Latest uploaded assets' => '最新のアップロードファイル',
  'Mime' => 'MIMEタイプ',
  'No asset selected' => 'ファイルが選択されていません',
  'No assets' => 'ファイルがありません',
  'Parent folder' => '親フォルダ',
  'Select' => '選択',
  'Upload asset' => 'ファイルをアップロード',
  'Upload failed for:' => 'アップロード失敗:',
  'none' => 'なし',
);