<?php return [
  'Create file' => 'ファイルを作成',
  'Create folder' => 'フォルダを作成',
  'Delete' => '削除',
  'Download' => 'ダウンロード',
  'Edit' => '編集',
  'Edit file' => 'ファイルを編集',
  'Empty' => '空',
  'File actions' => 'ファイルアクション',
  'File updated!' => 'ファイルが更新されました！',
  'File(s) deleted' => 'ファイルが削除されました',
  'File(s) size exceeds max upload size limit!' => 'ファイルサイズが最大アップロードサイズ制限を超えています！',
  'Finder' => 'ファインダー',
  'Folder actions' => 'フォルダアクション',
  'Item(s) deleted' => 'アイテムが削除されました',
  'Link file' => 'ファイルをリンク',
  'Name' => '名前',
  'No file linked' => 'ファイルがリンクされていません',
  'Readonly' => '読み取り専用',
  'Rename' => '名前を変更',
  'Reset' => 'リセット',
  'Select file' => 'ファイルを選択',
  'Settings' => '設定',
  'Size' => 'サイズ',
  'Updated' => '更新済み',
  'Upload failed!' => 'アップロードに失敗しました！',
  'Upload file' => 'ファイルをアップロード',
];
