<?php return [
  'Add event' => 'イベントを追加',
  'Add header' => 'ヘッダーを追加',
  'Create webhook' => 'webhookを作成',
  'Custom headers' => 'カスタムヘッダー',
  'Delete' => '削除',
  'Edit' => '編集',
  'Edit webhook' => 'webhookを編集',
  'Events' => 'イベント',
  'HTTP body' => 'HTTPボディ',
  'HTTP settings' => 'HTTP設定',
  'Name' => '名前',
  'No custom headers defined' => 'カスタムヘッダーが定義されていません',
  'No events defined' => 'イベントが定義されていません',
  'No webhooks' => 'webhookがありません',
  'Payload' => 'ペイロード',
  'Request Method' => 'リクエストメソッド',
  'Settings' => '設定',
  'Trigger webhook' => 'webhookをトリガー',
  'Update webhook' => 'webhookを更新',
  'Url' => 'URL',
  'Webhook created!' => 'webhookが作成されました！',
  'Webhook triggered!' => 'Webhookがトリガーされました！',
  'Webhook updated!' => 'Webhookが更新されました！',
  'Webhooks' => 'Webhooks',
];
