<?php return array (
  'Add header' => 'ヘッダーを追加',
  'Calling webhook url' => 'Webhook URLを呼び出し中',
  'Create webhook' => 'Webhookを作成',
  'Custom headers' => 'カスタムヘッダー',
  'Edit webhook' => 'Webhookを編集',
  'HTTP body' => 'HTTPボディ',
  'HTTP settings' => 'HTTP設定',
  'No custom headers defined' => 'カスタムヘッダーが定義されていません',
  'No webhooks' => 'Webhookがありません',
  'Payload' => 'ペイロード',
  'Request Method' => 'リクエストメソッド',
  'Trigger webhook' => 'Webhookをトリガー',
  'Update webhook' => 'Webhookを更新',
  'Webhook created!' => 'Webhookを作成しました！',
  'Webhook finished' => 'Webhook完了',
  'Webhook updated!' => 'Webhookを更新しました！',
  'Webhooks' => 'Webhook',
);