<?php return array (
  'All assets' => 'Tüm Varlıklar',
  'Asset actions' => 'Varlık Eylemleri',
  'Asset file updated!' => 'Varlık Dosyası Güncellendi!',
  'Asset link copied!' => 'Varlık Bağlantısı Kopyalandı!',
  'Asset removed!' => 'Varlık Kaldırıldı!',
  'Asset updated!' => 'Varlık Güncellendi!',
  'Assets removed!' => 'Varlıklar Kaldırıldı!',
  'Color copied!' => 'Renk Kopyalandı!',
  'Copy asset link' => 'Varlık Bağlantısını Kopyala',
  'Edit asset' => 'Varlığı Düzenle',
  'Folder' => 'Klasör',
  'Folder icon' => 'Klasör Simgesi',
  'Folder name' => 'Klasör Adı',
  'Folder name contains invalid characters' => 'Klasör adı geçersiz karakterler içeriyor',
  'Folder name is required' => 'Klasör adı gereklidir',
  'Folder removed!' => 'Klasör Kaldırıldı!',
  'Go to assets' => 'Varlıklara Git',
  'Latest uploaded assets' => 'Son Yüklenen Varlıklar',
  'Mime' => 'Mime',
  'No asset selected' => 'Varlık Seçilmedi',
  'No assets' => 'Varlık Yok',
  'Parent folder' => 'Üst Klasör',
  'Select' => 'Seç',
  'Upload asset' => 'Varlık Yükle',
  'Upload failed for:' => 'Yükleme Başarısız:',
  'none' => 'Hiçbiri',
);