<?php return array (
  'Add header' => 'Başlık Ekle',
  'Calling webhook url' => 'Webhook URL\'si Çağrılıyor',
  'Create webhook' => 'Webhook Oluştur',
  'Custom headers' => 'Özel Başlıklar',
  'Edit webhook' => 'Webhook\'u Düzenle',
  'HTTP body' => 'HTTP Gövdesi',
  'HTTP settings' => 'HTTP Ayarları',
  'No custom headers defined' => 'Özel Başlık Tanımlanmadı',
  'No webhooks' => 'Webhook Yok',
  'Payload' => 'Yük',
  'Request Method' => 'İstek Yöntemi',
  'Trigger webhook' => 'Webhook\'u Tetikle',
  'Update webhook' => 'Webhook\'u Güncelle',
  'Webhook created!' => 'Webhook Oluşturuldu!',
  'Webhook finished' => 'Webhook Tamamlandı',
  'Webhook updated!' => 'Webhook Güncellendi!',
  'Webhooks' => 'Webhooklar',
);