<?php return array (
  'All assets' => 'Все файлы',
  'Asset actions' => 'Действия с файлами',
  'Asset file updated!' => 'Файл обновлен!',
  'Asset link copied!' => 'Ссылка на файл скопирована!',
  'Asset removed!' => 'Файл удален!',
  'Asset updated!' => 'Файл обновлен!',
  'Assets removed!' => 'Файлы удалены!',
  'Color copied!' => 'Цвет скопирован!',
  'Copy asset link' => 'Копировать ссылку на файл',
  'Edit asset' => 'Редактировать файл',
  'Folder' => 'Папка',
  'Folder icon' => 'Иконка папки',
  'Folder name' => 'Имя папки',
  'Folder name contains invalid characters' => 'Имя папки содержит недопустимые символы',
  'Folder name is required' => 'Имя папки обязательно',
  'Folder removed!' => 'Папка удалена!',
  'Go to assets' => 'Перейти к файлам',
  'Latest uploaded assets' => 'Последние загруженные файлы',
  'Mime' => 'Mime',
  'No asset selected' => 'Файл не выбран',
  'No assets' => 'Нет файлов',
  'Parent folder' => 'Родительская папка',
  'Select' => 'Выбрать',
  'Upload asset' => 'Загрузить файл',
  'Upload failed for:' => 'Загрузка не удалась для:',
  'none' => 'нет',
);