<?php return array (
  'Add header' => 'Добавить заголовок',
  'Calling webhook url' => 'Вызов URL вебхука',
  'Create webhook' => 'Создать вебхук',
  'Custom headers' => 'Пользовательские заголовки',
  'Edit webhook' => 'Редактировать вебхук',
  'HTTP body' => 'HTTP тело',
  'HTTP settings' => 'Настройки HTTP',
  'No custom headers defined' => 'Пользовательские заголовки не определены',
  'No webhooks' => 'Нет вебхуков',
  'Payload' => 'Payload',
  'Request Method' => 'Метод запроса',
  'Trigger webhook' => 'Вызвать вебхук',
  'Update webhook' => 'Обновить вебхук',
  'Webhook created!' => 'Вебхук создан!',
  'Webhook finished' => 'Вебхук завершен',
  'Webhook updated!' => 'Вебхук обновлен!',
  'Webhooks' => 'Вебхуки',
);